# Generated by Django 3.0.8 on 2021-01-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0002_course_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Image de l'option",
            ),
        ),
    ]
