# Generated by Django 3.2.4 on 2021-08-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roommates", "0009_auto_20210805_1446"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roommates",
            name="banniere",
            field=models.ImageField(
                blank=True,
                help_text="Votre bannière sera affichée au format 1320x492 pixels.",
                null=True,
                upload_to="groups/banniere",
                verbose_name="Bannière",
            ),
        ),
        migrations.AlterField(
            model_name="roommates",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Votre logo sera affiché au format 306x306 pixels.",
                null=True,
                upload_to="groups/logo",
                verbose_name="Logo du groupe",
            ),
        ),
    ]
