# Generated by Django 3.2.13 on 2022-05-19 21:56

from django.db import IntegrityError, migrations, transaction


def create_setting(apps, schema_editor):
    Setting = apps.get_model("extra_settings", "Setting")
    try:
        with transaction.atomic():
            obj = Setting(
                name="PHASE_COLOCATHLON",
                value_type="int",
            )
            obj.value = 0
            obj.save()
    except IntegrityError:
        pass


def reverse_func(apps, schema_editor):
    Setting = apps.get_model("extra_settings", "Setting")
    try:
        with transaction.atomic():
            Setting.objects.get(name="PHASE_COLOCATHLON").delete()
    except IntegrityError:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("roommates", "0012_auto_20211021_1540"),
        ("extra_settings", "0005_setting_value_json_alter_setting_value_type"),
    ]

    operations = [
        migrations.RunPython(create_setting, reverse_func),
    ]
