# Generated by Django 4.2.23 on 2025-11-02 20:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("roommates", "0018_create_extra_setting_no_colocathlon_quota"),
        ("roommates", "0018_migrate_to_group"),
    ]

    operations = []
