# Generated by Django 4.2.28 on 2026-02-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0019_merge_20251102_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namedmembershiproommates',
            name='group',
        ),
        migrations.RemoveField(
            model_name='namedmembershiproommates',
            name='student',
        ),
        migrations.RemoveField(
            model_name='roommates',
            name='colocathlon_participants',
        ),
        migrations.RemoveField(
            model_name='roommates',
            name='housing',
        ),
        migrations.RemoveField(
            model_name='roommates',
            name='members',
        ),
        migrations.DeleteModel(
            name='Housing',
        ),
        migrations.DeleteModel(
            name='NamedMembershipRoommates',
        ),
        migrations.DeleteModel(
            name='Roommates',
        ),
    ]
