# Generated by Django 4.1.4 on 2023-02-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_baseevent_begin_inscription_baseevent_end_date'),
        ('student', '0006_alter_student_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='favorite_event',
            field=models.ManyToManyField(blank=True, null=True, to='event.baseevent', verbose_name='Événement en favoris'),
        ),
    ]
