# Generated by Django 4.1.7 on 2023-02-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_event_begin_inscription_event_end_date_and_more'),
        ('student', '0006_alter_student_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='favorite_event',
            field=models.ManyToManyField(blank=True, null=True, to='event.event', verbose_name='Événement en favoris'),
        ),
    ]
