# Generated by Django 4.2.4 on 2023-09-12 18:07

import apps.utils.fields.image_field
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0007_alter_student_faculty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="picture",
            field=apps.utils.fields.image_field.CustomImageField(
                blank=True,
                null=True,
                upload_to=apps.utils.fields.image_field.CustomImageField.create_filename,
                verbose_name="Photo de profil",
            ),
        ),
    ]
