# Generated by Django 4.1.4 on 2023-02-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_rename_ticketing_event_form_url'),
        ('student', '0007_student_favorite_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='favorite_event',
            field=models.ManyToManyField(blank=True, to='event.event', verbose_name='Événement en favoris'),
        ),
    ]
