# Generated by Django 4.2.23 on 2025-07-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sociallink", "0006_alter_sociallink_network"),
        ("student", "0009_student_description_student_social_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="social_links",
            field=models.ManyToManyField(blank=True, related_name="student_set", to="sociallink.sociallink", verbose_name="Social networks"),
        ),
    ]
