# Generated by Django 3.2.13 on 2022-07-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_double_account_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30)),
            ],
        ),
    ]
