# Generated by Django 3.2.15 on 2022-08-23 12:20

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_double_account_issue"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
    ]
