# Generated by Django 3.2.15 on 2022-08-22 19:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_idregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idregistration',
            name='key',
        ),
        migrations.AlterField(
            model_name='idregistration',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
