# Generated by Django 4.2.4 on 2023-09-03 16:05

from django.db import migrations


def change_user_type(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    ct = ContentType.objects.filter(app_label="auth", model="user").first()
    if ct:
        ct.app_label = "account"
        ct.save()


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_idregistration"),
    ]

    operations = [
        migrations.RunPython(change_user_type, elidable=True),
    ]
