# Generated by Django 4.2.4 on 2023-09-16 14:54

import datetime

import django.db.models.deletion
from django.db import migrations, models


def migrate_temporary_accounts(apps, schema_editor):
    TemporaryAccessRequest: models.Model = apps.get_model(
        "account", "TemporaryAccessRequest"
    )
    IdRegistration: models.Model = apps.get_model("account", "IdRegistration")
    invitation = IdRegistration.objects.first()

    for temp_account in TemporaryAccessRequest.objects.all():
        temp_account.user.invitation = invitation
        temp_account.save()


def migrate_temporary_accounts_back(apps, schema_editor):
    User: models.Model = apps.get_model("account", "User")
    TemporaryAccessRequest: models.Model = apps.get_model(
        "account", "TemporaryAccessRequest"
    )

    for user in User.objects.all():
        if user.invitation is not None:
            TemporaryAccessRequest.objects.create(
                user=user,
                final_email=user.email_next,
                domain="nantral-platform.fr",
                approved_until=user.invitation.expires_at,
                date=user.date_joined,
                approved=True,
                mail_valid=user.is_email_valid,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0009_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="idregistration",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 30, 23, 59)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="email_next",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="invitation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="account.idregistration",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_email_valid",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            migrate_temporary_accounts,
            reverse_code=migrate_temporary_accounts_back,
        ),
        migrations.DeleteModel(
            name="temporaryaccessrequest",
        ),
    ]
