# Generated by Django 4.2.4 on 2023-09-16 14:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0009_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="idregistration",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 16, 16, 54, 39, 732371)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="email_next",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="invitation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="account.idregistration",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_email_valid",
            field=models.BooleanField(default=False),
        ),
    ]
