# Generated by Django 4.2.21 on 2025-06-06 17:20

from django.db import migrations, models

from apps.account.utils import clean_username


def forwards(apps, schema_editor):
    User = apps.get_model("account", "User")

    for user in User.objects.all():
        user.username = clean_username(user.username)
        user.save()  # No duplicates because pk is included in the username


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0010_idregistration_expires_at_user_email_next_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={
                    "unique": "A user with that username already exists."
                },
                help_text="Required. 150 characters or fewer. Lower case letters, digits and ./_/=/-///+ only.",
                max_length=150,
                unique=True,
                verbose_name="username",
            ),
        ),
        migrations.RunPython(forwards),
    ]
