# Generated by Django 4.2.13 on 2024-08-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_idregistration_expires_at_user_email_next_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nantralpay_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
