# Generated by Django 4.2.23 on 2025-07-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0012_user_has_opened_matrix_user_has_updated_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={
                    "unique": "A user with that username already exists."
                },
                help_text="Required. 150 characters or fewer. Lower case letters, digits and ./_/-/+ only.",
                max_length=150,
                unique=True,
                verbose_name="username",
            ),
        ),
    ]
