# Generated by Django 4.2.23 on 2025-07-27 14:47

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.account.validators


def forwards(apps, schema_editor):
    User = apps.get_model("account", "User")
    Email = apps.get_model("account", "Email")

    for user in User.objects.all():
        Email.objects.create(email=user.email, is_valid=user.is_email_valid)


def backwards(apps, schema_editor):
    User = apps.get_model("account", "User")

    for user in User.objects.all():
        user.is_email_valid = user.emails.filter(email=user.email).is_active
        user.save()


class Migration(migrations.Migration):
    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_valid", models.BooleanField(default=False, verbose_name="Email vérifié\xa0?")),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True, verbose_name="Identifiant unique")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="emails", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(
            model_name="user",
            name="email_next",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_email_valid",
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(error_messages={"unique": "Ce nom d'utilisateur est déjà pris"}, help_text="Requis. 150 caractères ou moins. Lettres minuscules, chiffres et . _ - + seulement.", max_length=150, unique=True, validators=[apps.account.validators.MatrixUsernameValidator()], verbose_name="Nom d'utilisateur"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email principal"),
        ),
    ]

    dependencies = [
        ("account", "0013_alter_user_username"),
    ]

