# Generated by Django 4.2.23 on 2025-09-01 23:35

from django.db import migrations, models

import apps.account.validators


class Migration(migrations.Migration):
    dependencies = [
        (
            "account",
            "0015_alter_email_is_valid_alter_email_is_visible_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["last_name", "first_name", "username"]},
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "This username is already taken."},
                help_text="Required. 150 characters or fewer. Lower case letters, digits and ./_/-/+ only.",
                max_length=150,
                unique=True,
                validators=[apps.account.validators.validate_matrix_username],
                verbose_name="Username",
            ),
        ),
    ]
