# Generated by Django 4.2.28 on 2026-02-07 16:04

from django.db import migrations, models

import apps.utils.fields.image_field


class Migration(migrations.Migration):
    dependencies = [
        (
            "sociallink",
            "0007_remove_sociallink_network_remove_sociallink_slug_and_more",
        ),
        ("account", "0016_alter_user_options_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="user",
            name="faculty",
            field=models.CharField(
                choices=[
                    ("Gen", "Ingénieur Généraliste"),
                    ("Iti", "Ingénieur de Spécialité (ITII)"),
                    ("Mas", "Master"),
                    ("Doc", "Doctorat"),
                    ("Bac", "Bachelor"),
                    ("MSp", "Mastère Spécialisé"),
                ],
                default="Gen",
                max_length=200,
                verbose_name="Filière",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="path",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Cla", ""),
                    ("Alt", "Alternance"),
                    ("I-A", "Ingénieur-Architecte"),
                    ("A-I", "Architecte-Ingénieur"),
                    ("I-M", "Ingénieur-Manager"),
                    ("M-I", "Manager-Ingénieur"),
                    ("I-O", "Ingénieur-Officier"),
                    ("O-I", "Officier-Ingénieur"),
                ],
                max_length=200,
                null=True,
                verbose_name="Cursus",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="picture",
            field=apps.utils.fields.image_field.CustomImageField(
                blank=True, null=True, verbose_name="Photo de profil"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="promo",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Année de promotion entrante",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="social_links",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_set",
                to="sociallink.sociallink",
                verbose_name="Social networks",
            ),
        ),
    ]
