# Generated by Django 4.2.28 on 2026-02-07 15:43

from django.db import migrations


def forward(apps, schema_editor):
    Student = apps.get_model("student", "Student")
    User = apps.get_model("account", "User")

    for student in Student.objects.all():
        user = User.objects.get(id=student.user_id)
        user.promo = student.promo
        user.picture = student.picture
        user.faculty = student.faculty
        user.path = student.path
        user.description = student.description
        for social_link in student.social_links.all():
            user.social_links.create(
                uri=social_link.uri, label=social_link.label
            )
        user.save()


def reverse(apps, schema_editor):
    Student = apps.get_model("student", "Student")
    User = apps.get_model("account", "User")

    for user in User.objects.all():
        if not hasattr(user, "student"):
            user.student = Student.objects.create(user=user)
        student = user.student
        student.promo = user.promo
        student.picture = user.picture
        student.faculty = user.faculty
        student.path = user.path
        student.description = user.description
        for social_link in user.social_links.all():
            user.student.social_links.create(
                uri=social_link.uri, label=social_link.label
            )
        student.save()


class Migration(migrations.Migration):
    dependencies = [
        (
            "account",
            "0017_user_description_user_faculty_user_path_user_picture_and_more",
        ),
    ]

    operations = [migrations.RunPython(forward, reverse)]
