# Generated by Django 4.2.28 on 2026-02-08 00:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0018_auto_migrate_from_student_20260207_1643"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="has_opened_matrix",
        ),
        migrations.RemoveField(
            model_name="user",
            name="has_updated_username",
        ),
    ]
