# Generated by Django 5.2.17 on 2026-08-26 22:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0020_alter_user_faculty_alter_user_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Created at"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="email",
            name="last_reminder_sent",
            field=models.DateTimeField(blank=True, help_text="Tracks when the last verification reminder was sent", null=True, verbose_name="Last reminder sent"),
        ),
    ]
