# Generated by Django 3.2.3 on 2021-06-14 15:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("liste", "0003_liste_alt_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="liste",
            options={"ordering": ["-year", "liste_type", "name"]},
        ),
    ]
