# Generated by Django 3.2.4 on 2021-07-06 19:43

import apps.utils.upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liste', '0009_auto_20210703_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='liste',
            name='banniere',
            field=models.ImageField(blank=True, null=True, upload_to=apps.utils.upload.PathAndRename('groups/banniere/club'), verbose_name='Bannière'),
        ),
    ]
