# Generated by Django 4.2.20 on 2025-04-01 10:31

import apps.utils.fields.image_field
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0018_event_nantralpay_has_been_opened_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('creation_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('creation_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_list', to='event.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_intent_id', models.IntegerField(unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('checkout_date', models.DateTimeField(auto_now_add=True)),
                ('helloasso_order_id', models.IntegerField(null=True, unique=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_fr', models.CharField(max_length=255, null=True, unique=True)),
                ('name_en', models.CharField(max_length=255, null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', apps.utils.fields.image_field.CustomImageField(blank=True, null=True, verbose_name='Image')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_list', to='nantralpay.item')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nantralpay.transaction')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('scanned', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(related_name='sales', through='nantralpay.Content', to='nantralpay.item')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='nantralpay.seller')),
            ],
            bases=('nantralpay.transaction',),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nantralpay.transaction')),
                ('helloasso_payment_id', models.IntegerField(unique=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Authorized', 'Authorized'), ('Refused', 'Refused'), ('Unknown', 'Unknown'), ('Registered', 'Registered'), ('Refunded', 'Refunded'), ('Refunding', 'Refunding'), ('Contested', 'Contested')], default='Pending', max_length=255)),
                ('payment_cash_out_state', models.CharField(choices=[('CashedOut', 'Cashed Out'), ('WaitingForCashOutConfirmation', 'Waiting For Cash Out Confirmation'), ('Refunding', 'Refunding'), ('Refunded', 'Refunded'), ('TransfertInProgress', 'Transfert In Progress'), ('Transfered', 'Transfered'), ('MoneyIn', 'Money In')], default='MoneyIn', max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nantralpay.order')),
            ],
            bases=('nantralpay.transaction',),
        ),
        migrations.AddField(
            model_name='content',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='nantralpay.sale'),
        ),
        migrations.AddConstraint(
            model_name='content',
            constraint=models.UniqueConstraint(fields=('item', 'sale'), name='unique_item_sale'),
        ),
    ]
