# Generated by Django 4.2.13 on 2024-09-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nantralpay", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="qrtransaction",
            old_name="date",
            new_name="creation_date",
        ),
    ]
