# Generated by Django 4.2.20 on 2025-05-16 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nantralpay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 22, 25, 6, 772522, tzinfo=datetime.timezone.utc)),
        ),
    ]
