# Generated by Django 4.2.20 on 2025-05-17 10:01

import django.db.models.deletion
from django.db import migrations, models

import apps.nantralpay.models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0019_event_sellers_event_use_nantralpay"),
        ("nantralpay", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="event",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="event.event"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(choices=[("Saved", "Saved"), ("Pending", "Pending"), ("Canceled", "Canceled"), ("Completed", "Completed"), ("Validated", "Validated"), ("Unknown", "Unknown")], default="Saved", max_length=10),
        ),
        migrations.AlterField(
            model_name="qrcode",
            name="expiration_date",
            field=models.DateTimeField(default=apps.nantralpay.models.default_QRcode_expiration_date),
        ),
    ]
