# Generated by Django 4.2.13 on 2024-09-29 17:02

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nantralpay", "0002_rename_date_qrtransaction_creation_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qrtransaction",
            name="id",
        ),
        migrations.AddField(
            model_name="qrtransaction",
            name="transaction_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
