# Generated by Django 4.2.20 on 2025-05-17 07:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_event_sellers_event_use_nantralpay'),
        ('nantralpay', '0002_alter_qrcode_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 7, 48, 59, 12883, tzinfo=datetime.timezone.utc)),
        ),
    ]
