# Generated by Django 4.2.13 on 2025-03-11 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0014_group_nantralpay_balance_and_more"),
        ("nantralpay", "0005_qrcode_sale_transaction_delete_qrtransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="group.group",
            ),
        ),
    ]
