# Generated by Django 4.2.13 on 2025-03-12 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nantralpay", "0006_transaction_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="user",
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_cash_out_state",
            field=models.CharField(
                choices=[
                    ("CashedOut", "Cashed Out"),
                    (
                        "WaitingForCashOutConfirmation",
                        "Waiting For Cash Out Confirmation",
                    ),
                    ("Refunding", "Refunding"),
                    ("Refunded", "Refunded"),
                    ("TransfertInProgress", "Transfert In Progress"),
                    ("Transfered", "Transfered"),
                    ("MoneyIn", "Money In"),
                ],
                default="MoneyIn",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Authorized", "Authorized"),
                    ("Refused", "Refused"),
                    ("Unknown", "Unknown"),
                    ("Registered", "Registered"),
                    ("Refunded", "Refunded"),
                    ("Refunding", "Refunding"),
                    ("Contested", "Contested"),
                ],
                default="Pending",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="helloasso_payment_id",
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkout_intent_id", models.IntegerField(unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("checkout_date", models.DateTimeField(auto_now_add=True)),
                ("helloasso_order_id", models.IntegerField(null=True, unique=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="nantralpay.order",
            ),
            preserve_default=False,
        ),
    ]
