# Generated by Django 4.2.20 on 2025-03-23 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nantralpay", "0007_remove_payment_user_payment_payment_cash_out_state_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="description",
        ),
    ]
