# This is not the proper config, please make sure to replace "bar" and "foo" before restoring the config from this file.
authentication.fallback-admin.secret = "bar"
authentication.fallback-admin.user = "foo"
certificate.default.cert = "%{file:/data/certs/mail.nantral-platform.fr/cert.pem}%"
certificate.default.default = true
certificate.default.private-key = "%{file:/data/certs/mail.nantral-platform.fr/key.pem}%"
directory.internal.store = "rocksdb"
directory.internal.type = "internal"
server.auto-ban.abuse.rate = "35/1d"
server.auto-ban.auth.rate = "100/1d"
server.auto-ban.loiter.rate = "150/1d"
server.auto-ban.scan.paths.00 = "*.php*"
server.auto-ban.scan.paths.01 = "*.cgi*"
server.auto-ban.scan.paths.02 = "*.asp*"
server.auto-ban.scan.paths.03 = "*/wp-*"
server.auto-ban.scan.paths.04 = "*/php*"
server.auto-ban.scan.paths.05 = "*/cgi-bin*"
server.auto-ban.scan.paths.06 = "*xmlrpc*"
server.auto-ban.scan.paths.07 = "*../*"
server.auto-ban.scan.paths.08 = "*/..*"
server.auto-ban.scan.paths.09 = "*joomla*"
server.auto-ban.scan.paths.10 = "*wordpress*"
server.auto-ban.scan.paths.11 = "*drupal*"
server.auto-ban.scan.rate = "30/1d"
server.hostname = "mail.nantral-platform.fr"
server.http.hsts = true
server.http.permissive-cors = false
server.http.url = "protocol + '://' + config_get('server.hostname') + ':' + local_port"
server.http.use-x-forwarded = true
server.listener.http.bind = "[::]:8080"
server.listener.http.protocol = "http"
server.listener.https.bind = "[::]:443"
server.listener.https.protocol = "http"
server.listener.https.tls.implicit = true
server.listener.imap.bind = "[::]:143"
server.listener.imap.protocol = "imap"
server.listener.imaptls.bind = "[::]:993"
server.listener.imaptls.protocol = "imap"
server.listener.imaptls.proxy.override = true
server.listener.imaptls.proxy.trusted-networks.0 = "172.19.0.2"
server.listener.imaptls.proxy.trusted-networks.1 = "172.19.0.0/16"
server.listener.imaptls.tls.implicit = true
server.listener.pop3.bind = "[::]:110"
server.listener.pop3.protocol = "pop3"
server.listener.pop3s.bind = "[::]:995"
server.listener.pop3s.protocol = "pop3"
server.listener.pop3s.tls.implicit = true
server.listener.sieve.bind = "[::]:4190"
server.listener.sieve.protocol = "managesieve"
server.listener.smtp.bind = "[::]:25"
server.listener.smtp.protocol = "smtp"
server.listener.smtp.proxy.override = true
server.listener.smtp.proxy.trusted-networks.0 = "172.19.0.2"
server.listener.smtp.proxy.trusted-networks.1 = "172.19.0.0/16"
server.listener.submission.bind = "[::]:587"
server.listener.submission.protocol = "smtp"
server.listener.submissions.bind = "[::]:465"
server.listener.submissions.protocol = "smtp"
server.listener.submissions.proxy.override = true
server.listener.submissions.proxy.trusted-networks.0 = "172.19.0.2"
server.listener.submissions.proxy.trusted-networks.1 = "172.19.0.0/16"
server.listener.submissions.tls.implicit = true
server.max-connections = 8192
server.socket.backlog = 1024
server.socket.nodelay = true
server.socket.reuse-addr = true
server.socket.reuse-port = true
storage.blob = "rocksdb"
storage.data = "rocksdb"
storage.directory = "internal"
storage.fts = "rocksdb"
storage.lookup = "rocksdb"
store.rocksdb.compression = "lz4"
store.rocksdb.path = "/opt/stalwart-mail/data"
store.rocksdb.type = "rocksdb"
tracer.log.ansi = false
tracer.log.enable = true
tracer.log.level = "info"
tracer.log.path = "/opt/stalwart-mail/logs"
tracer.log.prefix = "stalwart.log"
tracer.log.rotate = "daily"
tracer.log.type = "log"
