# Generated by Django 4.1.4 on 2023-01-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0007_alter_namedmembershipcourse_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="namedmembershipcourse",
            name="year",
            field=models.IntegerField(
                default=2023, verbose_name="Année où cette formation a été suivie"
            ),
        ),
    ]
