# Generated by Django 3.2.4 on 2021-08-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Réponse'},
        ),
        migrations.AlterModelOptions(
            name='membershipfamily',
            options={'verbose_name': 'Membre'},
        ),
        migrations.RenameField(
            model_name='questiongroup',
            old_name='group_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='details_en',
            field=models.CharField(default=1, max_length=200, verbose_name='Infos (en)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='name_en',
            field=models.CharField(default=1, max_length=100, verbose_name='Nom (en))'),
            preserve_default=False,
        ),
    ]
