# Generated by Django 3.2.4 on 2021-08-09 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_createModelQuestions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['name'], 'verbose_name': 'Famille'},
        ),
        migrations.AlterModelOptions(
            name='membershipfamily',
            options={'ordering': ['student'], 'verbose_name': 'Membre'},
        ),
    ]
