# Generated by Django 3.2.4 on 2021-08-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionmember',
            options={'verbose_name': 'Question Membres', 'verbose_name_plural': 'Questions Membres'},
        ),
        migrations.RemoveField(
            model_name='basequestion',
            name='coeff',
        ),
        migrations.AddField(
            model_name='questionmember',
            name='coeff',
            field=models.IntegerField(default=1, verbose_name='Coeficient'),
            preserve_default=False,
        ),
    ]
