# Generated by Django 3.2.4 on 2021-08-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_auto_20210806_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiongroup',
            name='details',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Informations supplémentaires'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='details_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Infos (en)'),
        ),
    ]
