# Generated by Django 3.2.4 on 2021-08-09 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210801_1726'),
        ('family', '0002_auto_20210809_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipfamily',
            name='gender',
            field=models.CharField(choices=[('F', 'Féminin'), ('M', 'Masculin'), ('A', 'Autre')], max_length=1, null=True, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='membershipfamily',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='family.family'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membershipfamily',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='membershipfamily', to='student.student'),
            preserve_default=False,
        ),
    ]
