# Generated by Django 3.2.4 on 2021-08-10 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_createModelQuestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipfamily',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='family.family'),
        ),
        migrations.AlterField(
            model_name='questionfamily',
            name='equivalent',
            field=models.OneToOneField(blank=True, help_text="Question équivalente dans le questionnaire des membres. Laissez vide si vous                     souhaitez que cette question ne soit pas prise en compte dans l'algo.", null=True, on_delete=django.db.models.deletion.CASCADE, to='family.questionmember', verbose_name='Question équivalente'),
        ),
    ]
