# Generated by Django 3.2.4 on 2021-08-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_auto_20210806_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiongroup',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='Nom (en)'),
        ),
    ]
