# Generated by Django 3.2.4 on 2021-08-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_auto_20210810_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpage',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Informations supplémentaires'),
        ),
        migrations.AlterField(
            model_name='questionpage',
            name='details_en',
            field=models.TextField(blank=True, null=True, verbose_name='Infos (en)'),
        ),
    ]
