# Generated by Django 3.2.4 on 2021-08-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_basequestion_type_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basequestion',
            name='type_form',
            field=models.CharField(choices=[('1', 'Sélectionner une option'), ('2', 'Choisir Oui/Non'), ('3', "Choisir J'aime/J'aime pas/Ne sais pas")], default='1', max_length=1, verbose_name='Type de Question :'),
        ),
    ]
