# Generated by Django 3.2.4 on 2021-09-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_auto_20210829_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipfamily',
            name='itii',
            field=models.BooleanField(default=False),
        ),
    ]
