# Generated by Django 3.2.4 on 2021-10-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0004_membershipfamily_itii'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affichage',
            name='res_itii',
        ),
        migrations.AlterField(
            model_name='affichage',
            name='phase',
            field=models.IntegerField(choices=[(0, 'Tout masquer'), (1, 'Questionnaires 2A+'), (2, 'Questionnaires 1A et 2A+'), (3, 'Soirée de parrainage'), (4, 'Résultats du parrainage'), (5, 'Questionnaires ITII'), (6, 'Résultats ITII')], default=0),
        ),
    ]
