# Generated by Django 3.2.4 on 2021-08-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0004_alter_basequestion_type_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='order',
            field=models.IntegerField(default=1, help_text="Ordre d'apparition du groupe dans le questionnaire", verbose_name='Ordre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basequestion',
            name='type_form',
            field=models.CharField(choices=[('1', 'Choisir 1 option'), ('2', 'Choisir Oui/Non'), ('3', "Choisir J'aime/J'aime pas/Ne sais pas")], default='1', help_text='Le champ "valeur" des options est inutile pour les types Oui/Non et J/JP/NSP.', max_length=1, verbose_name='Type de Question :'),
        ),
        migrations.AlterField(
            model_name='option',
            name='value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valeur'),
        ),
    ]
