# Generated by Django 3.2.4 on 2021-08-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0005_auto_20210806_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipfamily',
            name='foreign_student',
            field=models.BooleanField(default=False, verbose_name='Êtes-vous un étudiant étranger ?'),
        ),
        migrations.AddField(
            model_name='membershipfamily',
            name='gender',
            field=models.CharField(choices=[('F', 'Féminin'), ('M', 'Masculin'), ('A', 'Autre')], default='A', max_length=1, verbose_name='Genre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershipfamily',
            name='itii',
            field=models.BooleanField(default=False, verbose_name='Êtes-vous un étudiant ITII ?'),
        ),
        migrations.AlterField(
            model_name='membershipfamily',
            name='name',
            field=models.CharField(blank=True, help_text="Nom de l'étudiant, à renseigner uniquement s'il n'est pas inscrit sur Nantral Platform", max_length=100, null=True, verbose_name='Nom (facultatif)'),
        ),
    ]
