# Generated by Django 3.2.4 on 2021-08-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210801_1726'),
        ('family', '0006_auto_20210806_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='members',
            field=models.ManyToManyField(related_name='family1', related_query_name='family2', through='family.MembershipFamily', to='student.Student'),
        ),
    ]
