# Generated by Django 3.2.4 on 2021-08-07 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210801_1726'),
        ('family', '0007_alter_family_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affichage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affichage', models.IntegerField(choices=[(0, 'Questionnaires Parrainage'), (1, 'Résultats Parrainage'), (2, 'Questionnaires Remixage'), (3, 'Résultats Remixage')])),
            ],
        ),
        migrations.RemoveField(
            model_name='membershipfamily',
            name='name',
        ),
        migrations.AddField(
            model_name='family',
            name='non_subscribed_members',
            field=models.CharField(blank=True, help_text='Si certains des membres de la famille ne sont pas inscrits sur Nantral Platform,             vous pouvez les ajouter ici. Séparez les noms par des VIRGULES !!!', max_length=300, null=True, verbose_name='Autres parrains'),
        ),
        migrations.AlterField(
            model_name='family',
            name='members',
            field=models.ManyToManyField(related_name='family', through='family.MembershipFamily', to='student.Student'),
        ),
        migrations.AlterField(
            model_name='membershipfamily',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='family.family'),
        ),
    ]
