# Generated by Django 3.2.4 on 2021-08-07 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0008_auto_20210807_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipfamily',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='family.family'),
        ),
    ]
