# Generated by Django 3.2.4 on 2021-08-07 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210801_1726'),
        ('family', '0010_auto_20210807_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipfamily',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='family.family'),
        ),
        migrations.AlterField(
            model_name='membershipfamily',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
