# Generated by Django 3.2.4 on 2021-08-07 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0012_alter_membershipfamily_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerfamily',
            old_name='family',
            new_name='answerer',
        ),
        migrations.RenameField(
            model_name='answermember',
            old_name='member',
            new_name='answerer',
        ),
    ]
