# Generated by Django 3.2.4 on 2021-08-07 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0013_auto_20210807_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerfamily',
            old_name='answerer',
            new_name='family',
        ),
        migrations.RenameField(
            model_name='answermember',
            old_name='answerer',
            new_name='member',
        ),
    ]
