# Generated by Django 3.2.4 on 2021-08-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0014_auto_20210807_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipfamily',
            name='mentor',
        ),
        migrations.AddField(
            model_name='membershipfamily',
            name='role',
            field=models.CharField(choices=[('1A', '1ère Année'), ('2A+', '2ème Année et plus')], default='2A+', max_length=3, verbose_name='Rôle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affichage',
            name='affichage',
            field=models.IntegerField(choices=[(0, 'Tout masquer'), (1, 'Questionnaires Parrainage'), (2, 'Résultats Parrainage'), (3, 'Questionnaires Remixage'), (4, 'Résultats Remixage')]),
        ),
    ]
