# Generated by Django 3.2.4 on 2021-08-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0016_auto_20210808_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionfamily',
            options={'ordering': ['order'], 'verbose_name': 'Question Familles', 'verbose_name_plural': 'Questions Familles'},
        ),
        migrations.AlterModelOptions(
            name='questionmember',
            options={'ordering': ['page', 'order'], 'verbose_name': 'Question Membres', 'verbose_name_plural': 'Questions Membres'},
        ),
        migrations.RenameField(
            model_name='basequestion',
            old_name='title',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='basequestion',
            old_name='title_en',
            new_name='label_en',
        ),
        migrations.AddField(
            model_name='basequestion',
            name='order',
            field=models.IntegerField(default=0, help_text="Ordre d'apparition de la question", verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='option',
            name='value',
            field=models.IntegerField(default=1, verbose_name='Valeur'),
            preserve_default=False,
        ),
    ]
