# Generated by Django 3.2.4 on 2021-08-08 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0017_auto_20210808_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['question', 'value']},
        ),
    ]
