# Generated by Django 3.0.8 on 2021-03-12 21:27

import apps.utils.upload
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.utils.upload.PathAndRename('posts/pictures'), verbose_name='Une image, une affiche en lien ?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 21, 27, 8, 737303), verbose_name='Date de publication'),
        ),
    ]
