# Generated by Django 3.2.3 on 2021-06-18 22:30

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_use_correct_default_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=djrichtextfield.models.RichTextField(verbose_name="Texte de l'annonce"),
        ),
    ]
