# Generated by Django 3.2.4 on 2021-08-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_temporaryaccessrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryaccessrequest',
            name='message_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
