# Generated by Django 3.2.5 on 2021-11-04 16:55

from django.db import migrations
from datetime import datetime


"""
Correct the duplicate of user accounts.
"""

def sort_user(u):
    if u.last_login:
        return u.last_login.timestamp()
    else:
        return datetime(1919, 1, 1).timestamp()


def forwards_func(apps, schema_editor):
    User = apps.get_registered_model('auth', 'User')
    for user in User.objects.all():
        if User.objects.filter(email=user.email).count() > 1:
            l = list(User.objects.filter(email=user.email))
            l.sort(key= sort_user)
            list_to_delete = l[:-1]
            for u in list_to_delete:
                u.delete()



class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_lower_all_accounts'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
