# Generated by Django 3.0.8 on 2021-01-13 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='wanted',
        ),
    ]
