# Generated by Django 3.0.8 on 2021-03-10 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_dd_cursus_add_alternant'),
        ('exchange', '0002_auto_20210223_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exchange', to='student.Student'),
        ),
    ]
