# Generated by Django 3.0.8 on 2021-01-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('exchange', '0002_remove_exchange_wanted'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='wanted',
            field=models.ManyToManyField(to='academic.Course'),
        ),
    ]
