# Generated by Django 3.0.8 on 2021-01-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_exchange_wanted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='wanted',
        ),
    ]
