# Generated by Django 3.2.4 on 2021-10-01 00:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', 'test_clubs_debug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namedmembershipclub',
            name='date_begin',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Date de début'),
        ),
    ]
