# Generated by Django 3.0.8 on 2020-11-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0004_baseevent_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseevent",
            name="slug",
            field=models.SlugField(
                null=True,
                unique=True,
                verbose_name="Slug de l'événement",
            ),
        ),
    ]
