# Generated by Django 3.0.14 on 2021-04-27 20:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0006_auto_20210405_1710"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseevent",
            name="publication_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Date de publication",
            ),
        ),
    ]
