# Generated by Django 4.1.3 on 2022-12-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_baseevent_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseevent',
            name='ticketing',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lien vers la billetterie'),
        ),
    ]
