# Generated by Django 4.1.6 on 2023-02-13 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_baseevent_ticketing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EatingEvent',
        ),
    ]
