# Generated by Django 4.1.4 on 2023-01-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0010_baseevent_max_participant_alter_baseevent_ticketing"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseevent",
            name="end_inscription",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de fin de l'inscription"
            ),
        ),
    ]
