# Generated by Django 4.1.7 on 2023-04-10 11:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import django_ckeditor_5.fields

import apps.utils.upload


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0011_group_can_pin'),
        ('student', '0006_alter_student_faculty'),
        ('event', '0011_rename_baseevent_event'),
    ]

    operations = [
        # rename publication_date
        migrations.RenameField(
            model_name='event',
            old_name='publication_date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        # rename start date
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(help_text='Enter date in format DD/MM/YYYY HH:MM', verbose_name='Start date'),
        ),
        # others
        migrations.RemoveField(
            model_name='event',
            name='color',
        ),
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ticketing',
        ),
        migrations.AddField(
            model_name='event',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, help_text='Users who have bookmarked this event.', related_name='bookmarked_events', to='student.student', verbose_name='Bookmarks'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='student.student'),
        ),
        migrations.AddField(
            model_name='event',
            name='end_registration',
            field=models.DateTimeField(blank=True, help_text='Users cannot register after this date.', null=True, verbose_name='End date for registration'),
        ),
        migrations.AddField(
            model_name='event',
            name='form_url',
            field=models.URLField(blank=True, verbose_name='Link to external form'),
        ),
        migrations.AddField(
            model_name='event',
            name='max_participant',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum number of participants'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_registration',
            field=models.DateTimeField(blank=True, help_text='Users cannot register before this date.', null=True, verbose_name='Start date for registration'),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='student.student'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Your banner will be displayed at 1320x492 pixels.', null=True, upload_to=apps.utils.upload.PathAndRename('posts/pictures'), verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participate_events', to='student.student', verbose_name='Participants'),
        ),
        migrations.AlterField(
            model_name='event',
            name='publicity',
            field=models.CharField(choices=[('Pub', 'Public - Visible par tous'), ('Mem', 'Membres uniquement - Visible uniquement par les membres du groupe')], max_length=200, verbose_name='Visibility'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
