# Generated by Django 4.1.4 on 2023-02-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_baseevent_end_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseevent',
            name='begin_inscription',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de début de l'inscription"),
        ),
        migrations.AddField(
            model_name='baseevent',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de fin de l'événement"),
        ),
    ]
