# Generated by Django 4.1.7 on 2023-02-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_rename_baseevent_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='begin_inscription',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de début de l'inscription"),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de fin de l'événement"),
        ),
        migrations.AddField(
            model_name='event',
            name='end_inscription',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de fin de l'inscription"),
        ),
        migrations.AddField(
            model_name='event',
            name='max_participant',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de places maximal'),
        ),
    ]
