# Generated by Django 4.1.4 on 2023-02-20 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_baseevent_begin_inscription_baseevent_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseevent',
            old_name='ticketing',
            new_name='form_url',
        ),
    ]
