# Generated by Django 4.1.4 on 2023-02-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_event_begin_inscription_event_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='ticketing',
            new_name='form_url',
        ),
    ]
