# Generated by Django 4.1.4 on 2023-02-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_rename_ticketing_event_form_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Par défaut une heure après la date de début', null=True, verbose_name="Date de fin de l'événement"),
        ),
    ]
