# Generated by Django 4.1.7 on 2023-04-10 12:23

from django.db import migrations, models
from django.utils import timezone


def add_end_dates(apps, schema_editor):
    Event = apps.get_model('event', 'Event')
    for event in Event.objects.all():
        event.end_date = event.start_date + timezone.timedelta(hours=1)
        event.save()


def remove_end_dates(apps, schema_editor):
    # Nothing to do here
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_group_slug_to_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, help_text='If empty, default to one hour after the start date.', verbose_name='End date of the event'),
        ),
        migrations.RunPython(
            code=add_end_dates,
            reverse_code=remove_end_dates
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='If empty, default to one hour after the start date.', verbose_name='End date of the event'),
        ),
    ]
