# Generated by Django 4.1.4 on 2023-02-28 13:42

from django.db import migrations, models
import django.db.models.deletion

def migrate_slugs_to_fk(apps, schema_editor) :
    Event = apps.get_model('event', 'Event')
    Group = apps.get_model('group', 'Group')
    for obj in Event.objects.all() :
        group_object = Group.objects.filter(slug = obj.group_slug)
        if group_object.exists() :
            obj.group = group_object.first()
        else :
            print("Club" , obj.group_slug , "non reconnu" )
            obj.group = Group.objects.all().first()
            print("Club mis à défaut à " + obj.group.name)
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_group_grouptype_tag_membership_label_and_more'),
        ('event', '0014_alter_event_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(null = True,on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='Organisateur'),
        ),
        migrations.AlterField(
            model_name='event',
            name='form_url',
            field=models.URLField(blank=True, null=True, verbose_name='Lien vers la billetterie'),
        ),
        migrations.RunPython(migrate_slugs_to_fk),
        migrations.RemoveField(
            model_name='event',
            name='group_slug',
        ),
        migrations.AlterField(
            model_name='event',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='Organisateur'),
        ),
    ]
