# Generated by Django 4.2.28 on 2026-02-07 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards(apps, schema_editor):
    Event = apps.get_model("event", "Event")

    for event in Event.objects.all():
        if event.created_by:
            event.created_by_user = event.created_by.user
        if event.updated_by:
            event.updated_by_user = event.updated_by.user
        for participant in event.participants.all():
            event.participants_users.add(participant.user)
        for bookmark in event.bookmarks.all():
            event.bookmarks_users.add(bookmark.user)
        event.save()


def reverse(apps, schema_editor):
    Event = apps.get_model("event", "Event")

    for event in Event.objects.all():
        if event.created_by_user:
            event.created_by = event.created_by_user.student
        if event.updated_by_user:
            event.updated_by = event.updated_by_user.student
        for participant_user in event.participants_users.all():
            event.participants.add(participant_user.student)
        for bookmark_user in event.bookmarks_users.all():
            event.bookmarks.add(bookmark_user.student)
        event.save()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("event", "0017_event_description_en_event_description_fr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="bookmarks_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who have bookmarked this event.",
                related_name="bookmarked_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Bookmarks",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="created_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="participants_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="participating_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Participants",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="updated_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(forwards, reverse),
    ]
