# Generated by Django 4.2.20 on 2025-04-01 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_event_nantralpay_has_been_opened_and_more'),
        ('nantralpay', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sellers',
            field=models.ManyToManyField(blank=True, help_text='Users who can sell items for this event.', related_name='selling_events', through='nantralpay.Seller', to=settings.AUTH_USER_MODEL, verbose_name='Sellers'),
        ),
        migrations.AddField(
            model_name='event',
            name='use_nantralpay',
            field=models.BooleanField(default=False, help_text='Enable NantralPay for this event.', verbose_name='Use NantralPay'),
        ),
    ]
