# Generated by Django 5.2.15 on 2026-08-25 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.event.models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0020_rename_bookmarks_users_event_bookmarks_and_more"),
        ("group", "0025_group_can_create_sport_event"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SportEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("date", models.DateTimeField(verbose_name="Date")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Location"
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "TRAINING"), (2, "COMPETITION")],
                        default=apps.event.models.SportEventType["TRAINING"],
                        verbose_name="Type",
                    ),
                ),
                (
                    "non_participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="non_participating_sport_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Non-participants",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="group.group",
                        verbose_name="Groupe",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="participating_sport_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Participants",
                    ),
                ),
            ],
        ),
    ]
