# Generated by Django 5.2.15 on 2026-08-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0021_sportevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="sportevent",
            name="description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="sportevent",
            name="description_fr",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description"
            ),
        ),
    ]
