# Generated by Django 5.2.15 on 2026-09-26 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0022_sportevent_description_en_sportevent_description_fr"),
    ]

    operations = [
        migrations.AddField(
            model_name="sportevent",
            name="parent",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child",
                to="event.sportevent",
                verbose_name="Previous occurrence",
            ),
        ),
    ]
