# Generated by Django 3.2.13 on 2022-07-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exchange',
        ),
    ]
