# Generated by Django 3.2.3 on 2021-06-16 09:15

from django.db import migrations, models


from django.core.exceptions import ObjectDoesNotExist


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Liste = apps.get_model("liste", "Liste")
    NamedMembershipList = apps.get_model("liste", "NamedMembershipList")
    db_alias = schema_editor.connection.alias
    listes = Liste.objects.using(db_alias).all()
    for liste in listes:
        for admin in liste.admins.all():
            try:
                membership = NamedMembershipList.objects.using(db_alias).get(
                    liste=liste,
                    student=admin
                )
                membership = NamedMembershipList.objects.get(
                    liste=liste,
                    student=admin
                )
                membership.admin = True
                membership.save()
            except ObjectDoesNotExist:
                NamedMembershipList.objects.using(db_alias).create(
                    liste=liste,
                    student=admin,
                    admin=True
                )


def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    Liste = apps.get_model("liste", "Liste")
    NamedMembershipList = apps.get_model("liste", "NamedMembershipList")
    db_alias = schema_editor.connection.alias
    for membership in NamedMembershipList.objects.using(db_alias).all():
        if membership.admin:
            liste = Liste.objects.using(db_alias).get(id=membership.club)
            liste.admins.add(membership.student)
            liste.save()


class Migration(migrations.Migration):

    dependencies = [
        ('liste', '0004_alter_liste_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedmembershiplist',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.RemoveField(
            model_name='liste',
            name='admins',
        ),
    ]
