# Generated by Django 3.2.4 on 2021-08-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liste', '0010_liste_banniere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namedmembershiplist',
            name='function',
            field=models.CharField(blank=True, max_length=200, verbose_name='Rôle (facultatif)'),
        ),
    ]
