# Generated by Django 4.1.4 on 2023-02-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pinned',
            field=models.BooleanField(blank=True, default=False, verbose_name='Épinglé'),
        ),
    ]
