# Generated by Django 4.1.4 on 2023-02-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='page_suggestion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lien vers une page de Nantral Platform'),
        ),
        migrations.AddField(
            model_name='post',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='Si le post est épinglé'),
        ),
    ]
