# Generated by Django 4.1.4 on 2023-02-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_page_suggestion_post_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='page_suggestion',
            field=models.URLField(blank=True, help_text='Lien vers une page web', null=True, verbose_name='Suggestion de page'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='Épinglé'),
        ),
    ]
