# Generated by Django 4.1.4 on 2023-02-28 15:15

from django.db import migrations, models
import django.db.models.deletion

def migrate_slugs_to_fk(apps, schema_editor) :
    Post = apps.get_model('post', 'Post')
    Group = apps.get_model('group', 'Group')
    for obj in Post.objects.all() :
        group_object = Group.objects.filter(slug = obj.group_slug)
        if group_object.exists() :
            obj.group = group_object.first()
        else :
            print("Club" , obj.group_slug , "non reconnu" )
            obj.group = Group.objects.all().first()
            print("Club mis à défaut à " + obj.group.name)
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('group','0010_group_grouptype_tag_membership_label_and_more'),
        ('post', '0008_alter_post_page_suggestion_alter_post_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(
                null = True,
                on_delete=django.db.models.deletion.CASCADE, 
                to='group.group', 
                verbose_name='Organisateur'),
        ),
        migrations.RunPython(migrate_slugs_to_fk),
        migrations.RemoveField(
            model_name='post',
            name='group_slug',
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, 
                to='group.group', 
                verbose_name='Organisateur'),
        ),
    ]      