# Generated by Django 4.1.4 on 2023-03-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_remove_post_description_remove_post_group_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edit_date',
            field=models.DateTimeField(auto_now=True, verbose_name="Date d'édition"),
        ),
    ]
