# Generated by Django 4.2.28 on 2026-02-07 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards(apps, schema_editor):
    Post = apps.get_model("post", "Post")

    for post in Post.objects.all():
        if post.created_by:
            post.created_by_user = post.created_by.user
        if post.updated_by:
            post.updated_by_user = post.updated_by.user
        post.save()


def reverse(apps, schema_editor):
    Post = apps.get_model("post", "Post")

    for post in Post.objects.all():
        if post.created_by_user:
            post.created_by = post.created_by_user.student
        if post.updated_by_user:
            post.updated_by = post.updated_by_user.student
        post.save()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0010_post_description_en_post_description_fr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="created_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="updated_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(forwards, reverse),
    ]
