# Generated by Django 4.2.28 on 2026-02-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_remove_post_created_by_remove_post_updated_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_by_user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_by_user',
            new_name='updated_by',
        ),
    ]
