# Generated by Django 4.1.7 on 2023-02-22 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_migrate_to_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='namedmembershipadministration',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='namedmembershipadministration',
            name='group',
        ),
        migrations.RemoveField(
            model_name='namedmembershipadministration',
            name='student',
        ),
        migrations.DeleteModel(
            name='Administration',
        ),
        migrations.DeleteModel(
            name='NamedMembershipAdministration',
        ),
    ]
