include:
  - stack/celery.yml
  - stack/postgres.yml
  - stack/redis.yml
  - stack/cache.yml

volumes:
  redis:

networks:
  proxy:
  database:
    internal: true
  redis:
    internal: true
  cache:
    internal: true
  celery:
    internal: true
