version: "2.1"

services:
  database:
    env_file: ../backend/config/settings/.env
    ports:
      - "5432:5432"

  backend:
    env_file: ../backend/config/settings/.env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.docker

  redis:
    restart: no

  nginx:
    build: ./containers/nginx_local

  celery:
    env_file: ../backend/config/settings/.env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.docker

  celery-beat:
    env_file: ../backend/config/settings/.env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.docker

  workers-dashboard:
    build:
      context: ../backend/
      dockerfile: ../deployment/containers/web/Dockerfile
    command: celery -A apps.celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - 5555:5555
    depends_on:
      - backend
      - redis
      - celery
    env_file: ../backend/config/settings/.env
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=config.settings.docker

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - 1025:1025
      - 8025:8025
