version: "2.1"

services:
  database:
    image: postgres:11.5
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  server:
    build:
      context: ../
      dockerfile: deployment/containers/web/Dockerfile
    expose:
      - 8000
    command: sh run_server.sh
    volumes:
      - ../server:/var/app
      - static_volume:/var/app/staticfiles/
    depends_on:
      - database
    environment:
      - DB_HOSTNAME
      - DB_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - DB_NAME
      - S3_BUCKET
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - GITHUB_USER
      - GITHUB_TOKEN
      - DJANGO_ALLOWED_HOSTS
      - SECRET_KEY
      - MAPBOX_API_KEY
      - DISCORD_TOKEN
      - DISCORD_CHANNEL_ID
      - DISCORD_ADMIN_MODERATION_WEBHOOK
      - TEMPORARY_ACCOUNTS_DATE_LIMIT

  nginx:
    build: ./containers/nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../server:/var/app
      - static_volume:/var/app/staticfiles/
      - /etc/letsencrypt:/etc/letsencrypt
      - /home/ubuntu/nantralPlatform/deployment/containers/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:rw
    depends_on:
      - server

  mail:
    build: ./containers/mailserver
    hostname: mailserver
    ports:
      - 81:80
      - 444:443
      - 110:110
      - 995:995
      - 143:143
      - 993:993
      - 25:25
      - 465:465
      - 587:587
    env_file:
      - ./containers/mailserver/mailserver.conf
    volumes:
      - /iredmail/data/backup-mysql:/var/vmail/backup/mysql
      - /iredmail/data/mailboxes:/var/vmail/vmail1
      - /iredmail/data/mlmmj:/var/vmail/mlmmj
      - /iredmail/data/mlmmj-archive:/var/vmail/mlmmj-archive
      - /iredmail/data/imapsieve_copy:/var/vmail/imapsieve_copy
      - /iredmail/data/custom:/opt/iredmail/custom
      - /iredmail/data/ssl:/opt/iredmail/ssl
      - /iredmail/data/mysql:/var/lib/mysql
      - /iredmail/data/clamav:/var/lib/clamav
      - /iredmail/data/sa_rules:/var/lib/spamassassin
      - /iredmail/data/postfix_queue:/var/spool/postfix
volumes:
  postgres_data:
  static_volume:
