include:
  - stack/celery.yml
  - stack/postgres.yml
  - stack/redis.yml
  - stack/traefik.yml
  - stack/nginx.yml
  - stack/backend.yml
  # - stack/mail.yml
  - stack/stalwart.yml

volumes:
  static_volume:
  static_volume_staging:
  redis:
  certs:

secrets:
  ovh_endpoint:
    file: "./secrets/ovh_endpoint.secret"
  ovh_application_key:
    file: "./secrets/ovh_application_key.secret"
  ovh_application_secret:
    file: "./secrets/ovh_application_secret.secret"
  ovh_consumer_key:
    file: "./secrets/ovh_consumer_key.secret"

networks:
  proxy:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24