version: "2.1"

services:
  database:
    image: postgres:11.5
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  server:
    build:
      context: ../
      dockerfile: deployment/containers/web/Dockerfile
    expose:
      - 8000
    command: sh run_server.sh
    volumes:
      - ../server:/var/app
      - static_volume:/var/app/staticfiles/
    depends_on:
      - database
    environment:
      - DB_HOSTNAME
      - DB_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - DB_NAME
      - S3_BUCKET
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - DJANGO_SETTINGS_MODULE=config.settings.docker
      - GITHUB_USER
      - GITHUB_TOKEN
      - MAPBOX_API_KEY
      - DISCORD_TOKEN
      - DISCORD_CHANNEL_ID
      - TEMPORARY_ACCOUNTS_DATE_LIMIT

  nginx:
    build: ./containers/nginx_http
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../server:/var/app
      - static_volume:/var/app/staticfiles/
    depends_on:
      - server

volumes:
  postgres_data:
  static_volume:
