version: "2.1"

services:
  database:
    image: postgres:11.5
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  dbbackup:
    image: kartoza/pg-backup:9.4
    hostname: db-backups
    volumes:
      - ./backups:/backups
    links:
      - database:database
    environment:
      - DUMPPREFIX=backup
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=5432
      - PGHOST=database
      - PGDATABASE=${POSTGRES_DB}
      - REMOVE_BEFORE=20

  server:
    build:
      context: ../
      dockerfile: deployment/containers/web/Dockerfile
    expose:
    - 8000
    command: sh run_server.sh
    volumes:
      - ../server:/var/app
      - static_volume:/var/app/staticfiles/
    depends_on:
      - database
    environment:
      - DB_HOSTNAME
      - DB_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - GITHUB_USER
      - GITHUB_TOKEN
      - DJANGO_ALLOWED_HOSTS
      - SECRET_KEY

  nginx:
    build: ./containers/nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../server:/var/app
      - static_volume:/var/app/staticfiles/
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - server

volumes:
  postgres_data:
  static_volume:
