# Generated by Django 3.2.3 on 2021-07-13 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nom du service')),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('proposed_by', models.SlugField()),
                ('conditions', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('paiment_link', models.URLField(blank=True, null=True, verbose_name='Lien de paiement')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(blank=True, null=True)),
                ('taken_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Availabilty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Début de la disponibilité')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Fin de la disponibilité')),
                ('quantity', models.IntegerField(default=1, verbose_name='Nombre de réservations possibles pour ce créneau.')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.service')),
            ],
        ),
    ]
