# Generated by Django 3.2.3 on 2021-07-24 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='paiment_link',
            new_name='payment_link',
        ),
    ]
