# Generated by Django 3.2.3 on 2021-07-24 20:36

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_paiment_link_service_payment_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Prix'),
        ),
    ]
