# Generated by Django 3.0.14 on 2021-05-24 21:44

import apps.utils.upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', 'group_admin_no_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.utils.upload.PathAndRename('./static/upload/groups/logo/club'), verbose_name='Logo du club'),
        ),
        migrations.AlterField(
            model_name='liste',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.utils.upload.PathAndRename('./static/upload/groups/logo/liste'), verbose_name='Logo de la liste'),
        ),
    ]
