# Generated by Django 3.0.5 on 2020-05-05 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nom du groupe')),
                ('description', models.TextField(blank=True, verbose_name='Description du groupe')),
                ('logo', models.CharField(blank=True, max_length=400, verbose_name='Lien vers le logo du groupe')),
                ('slug', models.SlugField(blank=True, max_length=40, unique=True)),
                ('bdx_type', models.CharField(choices=[('BDA', 'Bureau des arts'), ('BDE', 'Bureau des élèves'), ('BDS', 'Bureau des sports'), ('Asso', 'Association')], max_length=60, verbose_name='Type de club BDX')),
                ('admins', models.ManyToManyField(related_name='admins', to=settings.AUTH_USER_MODEL, verbose_name='Administrateurs du groupe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NamedMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(blank=True, max_length=200, verbose_name='Poste occupé')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Annee du poste')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.Club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(through='group.NamedMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
