# Generated by Django 3.0.14 on 2021-05-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_auto_20210524_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='abbr',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nom abrégé'),
        ),
        migrations.AddField(
            model_name='club',
            name='prefere_abbr',
            field=models.BooleanField(default=False, verbose_name='Utiliser le nom abrégé plutôt que le nom complet'),
        ),
    ]
