# Generated by Django 3.0.5 on 2020-06-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20200601_2109'),
        ('group', '0002_auto_20200521_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='admins',
            field=models.ManyToManyField(related_name='admins', to='student.Student', verbose_name='Administrateur.rice.s du groupe'),
        ),
        migrations.AlterField(
            model_name='club',
            name='bdx_type',
            field=models.CharField(choices=[('BDA', 'Bureau des Arts'), ('BDE', 'Bureau des Élèves'), ('BDS', 'Bureau des Sports'), ('Asso', 'Association')], max_length=60, verbose_name='Type de club BDX'),
        ),
        migrations.AlterField(
            model_name='namedmembership',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Année du poste'),
        ),
    ]
