# Generated by Django 3.2.3 on 2021-06-12 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_social_network_init'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='social',
        ),
        migrations.DeleteModel(
            name='LienSocialClub',
        ),
        migrations.DeleteModel(
            name='ReseauSocial',
        ),
    ]
