# Generated by Django 3.0.14 on 2021-05-29 17:05

import apps.utils.upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210524_2344'),
        ('group', '0003_auto_20210526_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='abbr',
        ),
        migrations.RemoveField(
            model_name='club',
            name='prefere_abbr',
        ),
        migrations.AddField(
            model_name='club',
            name='alt_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom abrégé'),
        ),
        migrations.AddField(
            model_name='club',
            name='banniere',
            field=models.ImageField(blank=True, null=True, upload_to=apps.utils.upload.PathAndRename('./static/upload/groups/banniere/club'), verbose_name='Bannière'),
        ),
        migrations.AddField(
            model_name='club',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='liste',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='club_admins', to='student.Student', verbose_name='Admins du groupe'),
        ),
        migrations.AlterField(
            model_name='liste',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='liste_admins', to='student.Student', verbose_name='Admins du groupe'),
        ),
        migrations.AlterField(
            model_name='reseausocial',
            name='color',
            field=models.CharField(max_length=7, verbose_name='Couleur en hexadécimal'),
        ),
    ]
