# Generated by Django 3.0.14 on 2021-06-10 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_social_network_init'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='bdx_type',
        ),
        migrations.RemoveField(
            model_name='club',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='liste',
            name='parent',
        ),
        migrations.AddField(
            model_name='club',
            name='BDX_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.Liste', verbose_name='Type de club BDX'),
        ),
        migrations.AlterField(
            model_name='liste',
            name='liste_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.Club', verbose_name='Type de BDX'),
        ),
    ]
