# Generated by Django 3.0.5 on 2020-06-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20200601_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='parent',
            field=models.SlugField(blank=True, max_length=40, null=True),
        ),
    ]
