# Generated by Django 3.0.14 on 2021-06-10 15:26

import apps.utils.upload
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_options'),
        ('group', '0004_auto_20210610_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='BDX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nom du groupe')),
                ('description', models.TextField(blank=True, verbose_name='Description du groupe')),
                ('slug', models.SlugField(blank=True, max_length=40, unique=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('alt_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom abrégé')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.utils.upload.PathAndRename('groups/logo/club'), verbose_name='Logo du club')),
                ('banniere', models.ImageField(blank=True, null=True, upload_to=apps.utils.upload.PathAndRename('groups/banniere/club'), verbose_name='Bannière')),
                ('admins', models.ManyToManyField(blank=True, related_name='bdx_admins', to='student.Student', verbose_name='Admins du groupe')),
            ],
            options={
                'verbose_name_plural': 'BDX',
            },
        ),
        migrations.CreateModel(
            name='NamedMembershipBDX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(blank=True, max_length=200, verbose_name='Poste occupé')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Année du poste')),
                ('BDX', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.BDX')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
            options={
                'unique_together': {('function', 'year', 'student', 'BDX')},
            },
        ),
        migrations.AddField(
            model_name='bdx',
            name='members',
            field=models.ManyToManyField(through='group.NamedMembershipBDX', to='student.Student'),
        ),
        migrations.AlterField(
            model_name='club',
            name='BDX_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.BDX', verbose_name='Type de club BDX'),
        ),
        migrations.AlterField(
            model_name='liste',
            name='liste_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.BDX', verbose_name='Type de BDX'),
        ),
    ]
