# Generated by Django 3.0.5 on 2020-06-10 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20200601_2121'),
        ('group', '0004_club_parent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='namedmembership',
            unique_together={('function', 'year', 'student', 'group')},
        ),
    ]
