# Generated by Django 3.2.3 on 2021-06-10 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_remove_social_network'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='liste',
                    name='admins',
                ),
                migrations.RemoveField(
                    model_name='liste',
                    name='members',
                ),
                migrations.RemoveField(
                    model_name='namedmembershipclub',
                    name='club',
                ),
                migrations.RemoveField(
                    model_name='namedmembershipclub',
                    name='student',
                ),
                migrations.RemoveField(
                    model_name='namedmembershiplist',
                    name='liste',
                ),
                migrations.RemoveField(
                    model_name='namedmembershiplist',
                    name='student',
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterUniqueTogether(
            name='namedmembershipclub',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='namedmembershiplist',
            unique_together=None,
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Club',
                ),
                migrations.DeleteModel(
                    name='Liste',
                ),
                migrations.DeleteModel(
                    name='NamedMembershipClub',
                ),
                migrations.DeleteModel(
                    name='NamedMembershipList',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Club',
                    table='club_club',
                ),
                migrations.AlterModelTable(
                    name='Liste',
                    table='liste_liste',
                ),
                migrations.AlterModelTable(
                    name='NamedMembershipClub',
                    table='club_namedmembershipclub',
                ),
                migrations.AlterModelTable(
                    name='NamedMembershipList',
                    table='liste_namedmembershipliste',
                ),
            ],
        )
    ]
