# Generated by Django 3.2.4 on 2021-08-06 09:39


from django.db import migrations
from apps.utils.compress import compressImage
from apps.group.models import Group
from apps.club.models import Club
from apps.liste.models import Liste
from apps.roommates.models import Roommates


def compress(model):
    for object in model.objects.all():
        try:
            object.logo = compressImage(object.logo, size=(500,500), contains=True)
            object.banniere = compressImage(object.banniere, size=(1320,492), contains=False)
            super(Group, object).save()
        except Exception:
            print("Fichier non existant")

def main_operations(apps, schema_editor):
    compress(Club)
    compress(Liste)
    compress(Roommates)


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_simplify_slug'),
        ('club', '0014_auto_20210806_1138'),
        ('liste', '0012_auto_20210806_1138'),
        ('roommates', '0010_auto_20210806_1138'),
    ]

    operations = [
        migrations.RunPython(main_operations),
    ]
