# Generated by Django 3.2.4 on 2021-09-08 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_auto_20210831_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminrightsrequest',
            name='uuid',
        ),
    ]
