# Generated by Django 3.2.3 on 2021-06-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sociallink", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sociallink",
            name="slug",
            field=models.SlugField(
                null=True, unique=True, verbose_name="Slug du lien"
            ),
        ),
    ]
