# Generated by Django 4.2.15 on 2024-09-16 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sociallink", "0005_alter_sociallink_label_alter_sociallink_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sociallink",
            name="network",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sociallink.socialnetwork",
                verbose_name="Type du lien",
            ),
        ),
    ]
