# Generated by Django 4.2.28 on 2026-02-07 16:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sociallink", "0006_alter_sociallink_network"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sociallink",
            name="network",
        ),
        migrations.RemoveField(
            model_name="sociallink",
            name="slug",
        ),
        migrations.DeleteModel(
            name="SocialNetwork",
        ),
    ]
