# Generated by Django 3.2.3 on 2021-06-10 21:33

import apps.utils.upload
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
        ('sociallink', '0001_initial'),
        ('student', '0003_alter_student_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nom du groupe')),
                ('description', models.TextField(blank=True, verbose_name='Description du groupe')),
                ('slug', models.SlugField(blank=True, max_length=40, unique=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Année de la liste')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.utils.upload.PathAndRename('groups/logo/liste'), verbose_name='Logo de la liste')),
                ('admins', models.ManyToManyField(blank=True, related_name='liste_admins', to='student.Student', verbose_name='Admins du groupe')),
                ('liste_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.bdx', verbose_name='Type de BDX')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NamedMembershipList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(blank=True, max_length=200, verbose_name='Poste occupé')),
                ('liste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liste.liste')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'unique_together': {('function', 'student', 'liste')},
            },
        ),
        migrations.AddField(
            model_name='liste',
            name='members',
            field=models.ManyToManyField(through='liste.NamedMembershipList', to='student.Student'),
        ),
        migrations.AddField(
            model_name='liste',
            name='social',
            field=models.ManyToManyField(to='sociallink.SocialLink'),
        ),
    ]
