# Generated by Django 3.2.3 on 2021-06-12 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_create_bdx'),
        ('liste', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liste',
            name='parent',
        ),
        migrations.AlterField(
            model_name='liste',
            name='liste_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.bdx'),
        ),
    ]
