# Generated by Django 3.2.3 on 2021-06-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liste', '0004_alter_liste_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liste',
            name='admins',
        ),
        migrations.AddField(
            model_name='namedmembershiplist',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
