# Generated by Django 3.2.3 on 2021-06-18 22:12

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('liste', '0007_liste_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liste',
            name='description',
            field=djrichtextfield.models.RichTextField(blank=True, verbose_name='Description du groupe'),
        ),
    ]
