services:
  backend:
    image: ghcr.io/3cn-ecn/nantralplatform:${BACKEND_TAG:-latest}
    expose:
      - "8000"
    command: sh run_server.sh
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - static_volume:/var/app/staticfiles/
    depends_on:
      - database
    env_file: ../backend.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`nantral-platform.fr`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
    networks:
      - proxy
      - database
      - cache

  backend-staging:
    image: ghcr.io/3cn-ecn/nantralplatform:${STAGING_TAG:-latest}
    expose:
      - "8000"
    command: sh run_server.sh
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - static_volume_staging:/var/app/staticfiles/
    depends_on:
      - database
      - memcached
    env_file: ../backend-staging.env
    environment:
      - STAGING=True
      - GUNICORN_WORKERS=1
      - "TZ=Europe/Paris"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-staging.rule=Host(`dev.nantral-platform.fr`)"
      - "traefik.http.routers.backend-staging.entrypoints=websecure"
      - "traefik.http.routers.backend-staging.tls.certresolver=letsencrypt"
    networks:
      - proxy
      - database
      - cache
