services:
  celery:
    image: ghcr.io/3cn-ecn/nantralplatform-celery:${BACKEND_TAG:-latest}
    command: uv run celery -A apps.celery worker -l info
    environment:
      - "TZ=Europe/Paris"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - celery-beat
      - redis
    env_file: ../backend.env
    networks:
      - celery
      - redis

  celery-beat:
    image: ghcr.io/3cn-ecn/nantralplatform-celery:${BACKEND_TAG:-latest}
    command: uv run celery -A apps.celery beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      - "TZ=Europe/Paris"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - redis
      - database
    env_file: ../backend.env
    networks:
      - celery
      - database
      - redis