services:
  nginx:
    container_name: nginx
    image: "nginx:1-alpine"
    restart: unless-stopped
    logging:
      driver: json-file
    environment:
      - "TZ=Europe/Paris"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - ../config/nginx/global_nginx.conf:/etc/nginx/nginx.conf
      - ../config/nginx/server_nginx.conf:/etc/nginx/conf.d/default.conf
      - ../config/nginx/custom_413.html:/var/www/html/custom_413.html
      - ../config/nginx/.well-known:/var/www/json/.well-known
      - static_volume:/var/app/staticfiles/
      - static_volume_staging:/var/app/staticfiles_staging/
    depends_on:
      - backend
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static-http.entrypoints=websecure"
      - "traefik.http.routers.static-http.rule=(Host(`nantral-platform.fr`) || Host(`dev.nantral-platform.fr`)) && (PathPrefix(`/static`) || PathPrefix(`/.well-known/matrix`))"
      - "traefik.http.routers.static-http.tls.certresolver=letsencrypt"
