services:
  database:
    image: postgres:14.1
    expose:
      - "5432"
    # environment:
      # - "TZ=Europe/Paris"
    volumes:
      # - "/etc/timezone:/etc/timezone:ro"
      # - "/etc/localtime:/etc/localtime:ro"
      - postgres_data:/var/lib/postgresql/data/
    env_file: ../backend.env
    networks:
      - proxy

volumes:
  postgres_data:
