services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    environment:
      - "TZ=Europe/Paris"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - redis:/data
    networks:
      - proxy
