# Generated by Django 3.0.14 on 2021-04-20 17:43

import apps.utils.upload
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_rename_dd_cursus_add_alternant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=250)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Roommates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nom du groupe')),
                ('description', models.TextField(blank=True, verbose_name='Description du groupe')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.utils.upload.PathAndRename('groups/logo/group'), verbose_name='Logo du groupe')),
                ('slug', models.SlugField(blank=True, max_length=40, unique=True)),
                ('parent', models.SlugField(blank=True, max_length=40, null=True)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('admins', models.ManyToManyField(blank=True, related_name='roommates_admins', to='student.Student', verbose_name='Administrateur.rice.s du groupe')),
                ('housing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommates.Housing')),
                ('members', models.ManyToManyField(related_name='roommates_members', to='student.Student', verbose_name='Membres du groupe')),
            ],
            options={
                'verbose_name_plural': 'Roommates',
            },
        ),
    ]
