# Generated by Django 3.0.14 on 2021-05-24 21:44

import apps.utils.upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommates',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.utils.upload.PathAndRename('./static/upload/groups/logo/group'), verbose_name='Logo du groupe'),
        ),
    ]
