# Generated by Django 3.0.14 on 2021-05-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210524_2344'),
        ('roommates', '0002_auto_20210524_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommates',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='roommates',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='roommates_admins', to='student.Student', verbose_name='Admins du groupe'),
        ),
    ]
