# Generated by Django 3.0.14 on 2021-06-08 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0002_auto_modified_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommates',
            name='parent',
        ),
    ]
