# Generated by Django 3.2.3 on 2021-06-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociallink', '0001_initial'),
        ('roommates', '0002_auto_modified_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommates',
            name='parent',
        ),
        migrations.AddField(
            model_name='roommates',
            name='social',
            field=models.ManyToManyField(to='sociallink.SocialLink'),
        ),
    ]
