# Generated by Django 3.2.3 on 2021-06-15 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0004_roommates_alt_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommates',
            name='begin_date',
            field=models.DateField(default=datetime.date.today, verbose_name="Date d'emménagement"),
        ),
        migrations.AlterField(
            model_name='roommates',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de sortie'),
        ),
    ]
