# Generated by Django 3.2.3 on 2021-06-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0005_auto_20210615_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommates',
            name='admins',
        ),
        migrations.AddField(
            model_name='namedmembershiproommates',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
