# Generated by Django 3.2.4 on 2021-07-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0008_auto_20210703_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommates',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom du groupe'),
        ),
    ]
