# Generated by Django 3.2.4 on 2021-08-04 22:06

import apps.utils.upload
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0009_alter_roommates_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommates',
            name='banniere',
            field=models.ImageField(blank=True, help_text='Votre photo sera affichée au format 1320x492 pixels.', null=True, upload_to=apps.utils.upload.PathAndRename('groups/banniere/roommates'), verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='address',
            field=models.CharField(max_length=250, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='details',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Complément d'adresse"),
        ),
        migrations.AlterField(
            model_name='namedmembershiproommates',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='roommates.roommates'),
            preserve_default=False,
        ),
    ]
