# Generated by Django 3.2.5 on 2021-10-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0011_alter_roommates_begin_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommates',
            name='colocathlon_activites',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Colocathlon : Activités proposées'),
        ),
        migrations.AddField(
            model_name='roommates',
            name='colocathlon_agree',
            field=models.BooleanField(default=False, verbose_name='Colocathlon : Participation au colocathlon'),
        ),
        migrations.AddField(
            model_name='roommates',
            name='colocathlon_cost',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Colocathlon : Prix demandé par participant'),
        ),
        migrations.AddField(
            model_name='roommates',
            name='colocathlon_hours',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Colocathlon : Horaires d'ouvertures"),
        ),
    ]
