# Generated by Django 3.2.5 on 2021-10-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210801_1726'),
        ('roommates', '0012_auto_20211015_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommates',
            name='colocathlon_participants',
            field=models.ManyToManyField(related_name='colocathlons_in', to='student.Student'),
        ),
    ]
