# Generated by Django 3.2.5 on 2021-10-15 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0012_auto_20211015_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roommates',
            old_name='colocathlon_activites',
            new_name='colocathlon_activities',
        ),
    ]
