version: '3.7'

x-server-env: &server-env
  DATABASE1_USERNAME: ${DATABASE1_USERNAME:-postgres}
  DATABASE1_PASSWORD: ${DATABASE1_PASSWORD:-nantral}
  DATABASE1_HOSTNAME: ${DATABASE1_HOSTNAME:-database1}
  DATABASE1_PORT: ${DATABASE1_PORT:-5432}

services:
  database1:
    image: postgres:11.5
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=nantral
  server:
    build:
      context: ../..
      dockerfile: containers/server/Dockerfile
    volumes:
      - ./logs/server:/var/app/logs
      - ../../server:/var/app
      - ../../static:/www/static
    expose:
      - "8000"
    ports:
      - "5001:8000"
    command: sh -c "/var/app/server-init.sh && /var/app/runserver.sh"
    depends_on:
      - database1
    environment:
      <<: *server-env