# Generated by Django 3.2.12 on 2022-04-21 18:09

from django.db import migrations, transaction


def forwards_func(apps, schema_editor):
    """Subscribe all users to the BDX"""
    Subscription = apps.get_model("notification", "Subscription")
    BDX = apps.get_model("club", "BDX")
    Student = apps.get_model("student", "Student")
    with transaction.atomic():
        Subscription.objects.bulk_create(
            objs=[
                Subscription(student=student, page="club--" + bdx.slug)
                for student in Student.objects.all()
                for bdx in BDX.objects.all()
            ],
            ignore_conflicts=True,
        )


def reverse_func(apps, schema_editor):
    """Unsubscribe all users from the BDX"""
    Subscription = apps.get_model("notification", "Subscription")
    BDX = apps.get_model("club", "BDX")
    with transaction.atomic():
        for bdx in BDX.objects.all():
            Subscription.objects.filter(page="club--" + bdx.slug).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0001_initial"),
        ("club", "0015_auto_20210819_2352"),
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
