# Generated by Django 4.2.13 on 2024-05-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0004_delete_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="icon_url",
            field=models.CharField(blank=True, default="", max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notification",
            name="image_url",
            field=models.CharField(blank=True, default="", max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notificationaction",
            name="icon_url",
            field=models.CharField(
                blank=True,
                default="",
                max_length=512,
                verbose_name="Url of the icon for the action",
            ),
            preserve_default=False,
        ),
    ]
