# Generated by Django 4.2.28 on 2026-02-07 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forward(apps, schema_editor):
    SentNotification = apps.get_model("notification", "SentNotification")

    for sent_notification in SentNotification.objects.all():
        sent_notification.user = sent_notification.student.user
        sent_notification.save()


def reverse(apps, schema_editor):
    SentNotification = apps.get_model("notification", "SentNotification")

    for sent_notification in SentNotification.objects.all():
        sent_notification.student = sent_notification.user.student
        sent_notification.save()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notification", "0005_alter_notification_icon_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentnotification",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(forward, reverse),
    ]
