# Generated by Django 4.2.28 on 2026-02-07 17:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notification", "0006_sentnotification_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sentnotification",
            unique_together={("user", "notification")},
        ),
        migrations.AlterField(
            model_name="notification",
            name="receivers",
            field=models.ManyToManyField(related_name="notification_set", through="notification.SentNotification", to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name="sentnotification",
            name="student",
        ),
    ]
