# Generated by Django 3.2.3 on 2021-06-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_create_bdx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bdx',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['bdx_type', 'name']},
        ),
        migrations.AlterField(
            model_name='club',
            name='alt_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom alternatif'),
        ),
    ]
