# Generated by Django 3.2.3 on 2021-06-16 07:10

import datetime
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_options'),
        ('club', '0004_alter_club_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bdx',
            options={'ordering': ['order'], 'verbose_name_plural': 'BDX'},
        ),
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('bdx_type'), nulls_first=True), 'name']},
        ),
        migrations.AddField(
            model_name='bdx',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='namedmembershipclub',
            name='date_begin',
            field=models.DateField(default=datetime.date.today, verbose_name='Date de début'),
        ),
        migrations.AddField(
            model_name='namedmembershipclub',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AddField(
            model_name='namedmembershipclub',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Hiérarchie'),
        ),
        migrations.AlterUniqueTogether(
            name='namedmembershipclub',
            unique_together={('function', 'date_begin', 'student', 'club')},
        ),
        migrations.RemoveField(
            model_name='namedmembershipclub',
            name='year',
        ),
    ]
