# Generated by Django 3.2.3 on 2021-06-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_alter_club_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bdx',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='bdx',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
