# Generated by Django 3.2.3 on 2021-06-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_auto_20210616_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='admins',
        ),
        migrations.AddField(
            model_name='namedmembershipclub',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
