# Generated by Django 3.2.3 on 2021-06-16 06:34

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_auto_20210615_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('bdx_type'), nulls_first=True), 'name']},
        ),
    ]
