import { EventProps } from '../../../Props/Event';

export function createTestEvent(
  slug = 'The slug',
  title = 'The test event',
  beginDate = new Date('2023-02-17T03:24:00'),
  endDate = new Date('2023-02-17T04:24:00'),
  description = 'This is an event to test',
  effectiveSize = 1,
  globalSize = 1,
  position = 0,
  placed = false,
  getAbsoluteUrl = 'https://nantral-platform.fr/account/login/?next=/',
  image = null,
  color = 'blue',
  isMember = true,
  isParticipating = true,
  location = 'My home',
  numberOfParticipants = 15,
  publicity: 'Pub' = 'Pub',
  maxParticipant = null,
  endRegistration = null,
  startRegistration = null,
  formUrl = null,
  isFavorite = true,
  group = {
    id: 1,
    name: 'group1',
    short_name: 'g1',
    slug: 'g1',
    icon: null,
    url: '/group/g1',
  }
) {
  const event: EventProps = {
    color: color,
    beginDate: beginDate,
    endDate: endDate,
    description: description,
    getAbsoluteUrl: getAbsoluteUrl,
    group: group,
    image: image,
    isMember: isMember,
    isParticipating: isParticipating,
    location: location,
    numberOfParticipants: numberOfParticipants,
    publicity: publicity,
    slug: slug,
    title: title,
    maxParticipant: maxParticipant,
    endRegistration: endRegistration,
    startRegistration: startRegistration,
    formUrl: formUrl,
    isFavorite: isFavorite,
    effectiveSize: effectiveSize,
    globalSize: globalSize,
    position: position,
    placed: placed,
    isAdmin: false,
  };

  return event;
}
