"""
Django settings for nantralPlatform project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

from datetime import datetime
import os
import environ
from django.urls import reverse_lazy
env = environ.Env()
# reading .env file
environ.Env.read_env()

# Build paths inside the project like this: join(BASE_DIR, "directory")
BASE_PATH = environ.Path(__file__) - 3
BASE_DIR = str(BASE_PATH)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/


secret = environ.Env(
    GOOGLE_API_KEY=(str, ""),
    DB_HOSTNAME=(str, ""),
    DB_PORT=(str, ""),
    POSTGRES_USER=(str, ""),
    POSTGRES_PASSWORD=(str, ""),
    DB_NAME=(str, "")
)


# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    'crispy_forms',
    'crispy_bootstrap5',
    'storages',
    'rest_framework',
    'django_ckeditor_5',
    'debug_toolbar',
    'django_celery_beat',
    'extra_settings',
]

COMMON_APPS = [
    'apps.account',
    'apps.student',
    'apps.home',
    'apps.group',
    'apps.liste',
    'apps.club',
    'apps.academic',
    'apps.event',
    'apps.services',
    'apps.exchange',
    'apps.post',
    'apps.roommates',
    'apps.sociallink',
    'apps.family',
    'apps.administration',
]

INSTALLED_APPS = DJANGO_APPS + COMMON_APPS + THIRD_PARTY_APPS

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'apps.account.emailAuthBackend.EmailBackend',
    "django.contrib.auth.backends.ModelBackend",
]


MESSAGE_STORAGE = 'django.contrib.messages.storage.cookie.CookieStorage'

ROOT_URLCONF = 'config.urls'
LOGIN_REDIRECT_URL = 'None'
LOGIN_URL = reverse_lazy('account:login')

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.home.context_processors.navbar_context'
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Choose default type for primary keys in models

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Richtext config

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|', '|',
            'bold', 'italic', 'underline', 'strikethrough', 
            'subscript', 'superscript', 'fontColor', 'fontBackgroundColor', 'removeFormat', '|',
            'alignment', 'bulletedList', 'numberedList', '|',
            'code', 'blockQuote', '|',
            'link', 'imageUpload', 'mediaEmbed', 'insertTable',
        ],
        'language': 'fr',
        'image': {
            'toolbar': ['imageTextAlternative', 'imageTitle', '|', 'imageStyle:alignLeft', 'imageStyle:full',
                        'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side',  '|'],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]

        },
        'table': {
            'contentToolbar': [ 'tableColumn', 'tableRow', 'mergeTableCells',
            'tableProperties', 'tableCellProperties' ]
        },
        'heading' : {
            'options': [
                { 'model': 'paragraph', 'title': 'Paragraphe', 'class': 'ck-heading_paragraph' },
                { 'model': 'heading1', 'view': 'h2', 'title': 'Titre 1', 'class': 'ck-heading_heading1' },
                { 'model': 'heading2', 'view': 'h3', 'title': 'Titre 2', 'class': 'ck-heading_heading2' },
                { 'model': 'heading3', 'view': 'h4', 'title': 'Titre 3', 'class': 'ck-heading_heading3' }
            ]
        },
        'link': {
            'addTargetToExternalLinks': True,  # open in new tab by default
            'defaultProtocol': 'https://',     # add https when missing
            'decorators': {                    # check-box in options
                'openInNewTab': {
                    'mode': 'manual',
                    'label': 'Ouvrir dans un nouvel onglet',
                    'attributes': {
                        'target': '_blank',
                        'rel': 'noopener noreferrer'
                    }
                }
            }
        },
        'mediaEmbed': {
            'previewsInData': True
        }
    }
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Discord connection
DISCORD_TOKEN = env('DISCORD_TOKEN', default='')
DISCORD_SERVER = env('DISCORD_SERVER', default='')
DISCORD_CHANNEL_ID = env('DISCORD_CHANNEL_ID', default='')


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

GITHUB_REPO = 'nantral-platform/nantralPlatform'

# Less origin restrictive for Youtube embed videos
SECURE_REFERRER_POLICY = "no-referrer-when-downgrade"

TEMPORARY_ACCOUNTS_DATE_LIMIT = datetime.fromisoformat(
    env('TEMPORARY_ACCOUNTS_DATE_LIMIT', default='2000-12-31'))
