# Generated by Django 3.0.5 on 2020-05-08 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0003_auto_20200508_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la formation')),
                ('course_type', models.CharField(choices=[('OD', 'Option disciplinaire'), ('OP', 'Option professionnelle'), ('ITII', 'Filliere de specialité'), ('Master', 'Master')], max_length=200, verbose_name='Type de cours')),
            ],
        ),
        migrations.CreateModel(
            name='FollowCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.CharField(choices=[('EI2', 'EI2'), ('EI3', 'EI3'), ('ITII', 'ITII'), ('M1', 'M1'), ('M2', 'M2')], max_length=200, verbose_name='Cours suivi en')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
