# Generated by Django 3.2.12 on 2022-04-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_auto_20210926_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namedmembershipcourse',
            name='year',
            field=models.IntegerField(default=2022, verbose_name='Année où cette formation a été suivie'),
        ),
    ]
