# Generated by Django 3.2.3 on 2021-06-05 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0003_alter_student_options"),
        ("group", "0001_adminrightsrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReseauSocial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Nom")),
                (
                    "color",
                    models.CharField(
                        max_length=7,
                        verbose_name="Couleur en hexadécimal",
                    ),
                ),
                (
                    "icon_name",
                    models.CharField(
                        max_length=20,
                        verbose_name="Nom Bootstrap de l'icône",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réseau Social",
                "verbose_name_plural": "Réseaux Sociaux",
            },
        ),
        migrations.AddField(
            model_name="club",
            name="alt_name",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Nom abrégé",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="banniere",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="groups/banniere/club",
                verbose_name="Bannière",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="liste",
            name="modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="club",
            name="admins",
            field=models.ManyToManyField(
                blank=True,
                related_name="club_admins",
                to="student.Student",
                verbose_name="Admins du groupe",
            ),
        ),
        migrations.AlterField(
            model_name="liste",
            name="admins",
            field=models.ManyToManyField(
                blank=True,
                related_name="liste_admins",
                to="student.Student",
                verbose_name="Admins du groupe",
            ),
        ),
        migrations.CreateModel(
            name="LienSocialClub",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=200, verbose_name="URL")),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="group.club",
                    ),
                ),
                (
                    "reseau",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="group.reseausocial",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="club",
            name="social",
            field=models.ManyToManyField(
                through="group.LienSocialClub",
                to="group.ReseauSocial",
            ),
        ),
    ]
