# Generated by Django 4.1.7 on 2023-02-20 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_group_membership_grouptype_group_group_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='children_name',
            field=models.CharField(default='Sub-groups', max_length=50, verbose_name='Children groups label'),
        ),
        migrations.AlterField(
            model_name='group',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='group.group', verbose_name='Parent group'),
        ),
    ]
