# Generated by Django 4.1.3 on 2022-12-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_group_grouptype_membership_group_members_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Groupe'},
        ),
    ]
