# Generated by Django 4.1.7 on 2023-02-20 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0011_group_children_name_alter_group_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='children_name',
            new_name='children_label',
        ),
    ]
