# Generated by Django 4.1.3 on 2022-12-17 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0011_alter_group_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouptype',
            options={'verbose_name': 'Type de groupe', 'verbose_name_plural': 'Types de groupes'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['group', 'order', 'student'], 'verbose_name': 'Membre'},
        ),
        migrations.RenameField(
            model_name='group',
            old_name='type',
            new_name='group_type',
        ),
    ]
