# Generated by Django 4.1.3 on 2022-12-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0011_grouptype_map_group_created_by_group_group_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Nom abrégé'),
            preserve_default=False,
        ),
    ]
