# Generated by Django 4.1.3 on 2023-01-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociallink', '0005_alter_sociallink_label_alter_sociallink_url'),
        ('group', '0012_alter_group_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouptype',
            name='anyone_can_join',
        ),
        migrations.AddField(
            model_name='group',
            name='social_links',
            field=models.ManyToManyField(related_name='+', to='sociallink.sociallink', verbose_name='Réseaux Sociaux'),
        ),
        migrations.AlterField(
            model_name='group',
            name='anyone_can_join',
            field=models.BooleanField(default=True, help_text="Affiche le bouton 'Devenir membre' pour tout le monde.", verbose_name='Adhésion libre'),
        ),
        migrations.AlterField(
            model_name='group',
            name='archived',
            field=models.BooleanField(default=False, help_text='Un groupe archivé ne peut plus avoir de nouveaux membres et est masqué des résultats par défaut.', verbose_name='Groupe archivé'),
        ),
    ]
