# Generated by Django 4.2.13 on 2025-03-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0013_alter_group_video1_alter_group_video2"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="nantralpay_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="membership",
            name="can_use_nantralpay",
            field=models.BooleanField(default=False),
        ),
    ]
