# Generated by Django 4.2.13 on 2024-08-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        (
            "group",
            "0014_rename_admin_request_messsage_membership_admin_request_message_and_more",
        ),
        ("group", "0015_grouptype_can_have_parent"),
        ("group", "0016_grouptype_priority"),
    ]

    dependencies = [
        ("sociallink", "0005_alter_sociallink_label_alter_sociallink_url"),
        ("group", "0013_alter_group_video1_alter_group_video2"),
    ]

    operations = [
        migrations.RenameField(
            model_name="membership",
            old_name="admin_request_messsage",
            new_name="admin_request_message",
        ),
        migrations.AlterField(
            model_name="group",
            name="social_links",
            field=models.ManyToManyField(
                blank=True,
                related_name="group_set",
                to="sociallink.sociallink",
                verbose_name="Social networks",
            ),
        ),
        migrations.AddField(
            model_name="grouptype",
            name="can_have_parent",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="grouptype",
            name="priority",
            field=models.IntegerField(default=0, verbose_name="Priority"),
        ),
    ]
