# Generated by Django 4.1.3 on 2023-01-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0013_remove_grouptype_anyone_can_join_group_social_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='public',
            field=models.BooleanField(default=False, help_text='Si coché, la page du groupe sera accessible publiquement, y compris à des utilisateurs non-connectés. Les membres, évènements et posts restent toutefois masqués.', verbose_name='Public'),
        ),
    ]
