# Generated by Django 4.1.5 on 2023-01-10 18:43

import apps.utils.upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0014_group_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptype',
            name='icon',
            field=models.ImageField(blank=True, help_text='Votre logo sera affiché au format 306x306 pixels.', null=True, upload_to=apps.utils.upload.PathAndRename('groups/logo'), verbose_name='Logo du type de groupe'),
        ),
    ]
