# Generated by Django 4.2.13 on 2024-08-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "group",
            "0014_rename_admin_request_messsage_membership_admin_request_message_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="grouptype",
            name="can_have_parent",
            field=models.BooleanField(default=True),
        ),
    ]
