# Generated by Django 4.1.5 on 2023-01-14 16:25

import apps.utils.upload
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
        ('group', '0015_grouptype_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouptype',
            old_name='group_by_label',
            new_name='category_label',
        ),
        migrations.RemoveField(
            model_name='grouptype',
            name='group_by_field',
        ),
        migrations.AddField(
            model_name='grouptype',
            name='category_field',
            field=models.CharField(blank=True, help_text='Nom du champ pour catégoriser les groupes dans la liste des groupes.', max_length=30, verbose_name='Catégoriser par'),
        ),
        migrations.AlterField(
            model_name='group',
            name='anyone_can_join',
            field=models.BooleanField(default=True, help_text="Affiche le bouton 'Devenir membre' pour tout le monde. Si décoché, seuls les admins pourront ajouter de nouveaux membres.", verbose_name='Adhésion libre'),
        ),
        migrations.AlterField(
            model_name='group',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='Groupe parent'),
        ),
        migrations.AlterField(
            model_name='group',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.place', verbose_name='Lieu lié au groupe'),
        ),
        migrations.AlterField(
            model_name='group',
            name='public',
            field=models.BooleanField(default=False, help_text='Si coché, la page du groupe sera accessible publiquement, y compris à des utilisateurs non-connectés. Les membres, évènements et posts restent toutefois masqués.', verbose_name='Groupe public'),
        ),
        migrations.AlterField(
            model_name='group',
            name='short_name',
            field=models.CharField(blank=True, help_text='Ce nom sera affiché dans la liste des groupes.', max_length=20, verbose_name='Nom raccourci'),
        ),
        migrations.AlterField(
            model_name='group',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Résumé'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grouptype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=apps.utils.upload.PathAndRename('groups/types'), verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='grouptype',
            name='is_year_group',
            field=models.BooleanField(default=False, help_text='Les groupes sont liés à une année scolaire. Aucunes dates ne sont demandées aux membres.', verbose_name='Groupes annuels.'),
        ),
        migrations.AlterField(
            model_name='grouptype',
            name='map',
            field=models.ForeignKey(blank=True, default=False, help_text='Les groupes peuvent avoir un lieu uniquement si une carte est liée.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.map', verbose_name='Carte liée'),
        ),
        migrations.AlterField(
            model_name='grouptype',
            name='place_required',
            field=models.BooleanField(default=False, help_text='Uniquement si une carte est liée.', verbose_name='Lieu obligatoire'),
        ),
        migrations.AlterField(
            model_name='grouptype',
            name='slug_is_name',
            field=models.BooleanField(default=True, help_text='Par défaut, le nom du groupe est utilisé pour construire le slug.', verbose_name='Slug basé sur le nom'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Résumé'),
            preserve_default=False,
        ),
    ]
