# Generated by Django 4.2.20 on 2025-03-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0014_group_nantralpay_balance_and_more"),
        ("group", "0014_rename_admin_request_messsage_membership_admin_request_message_and_more_squashed_0016_grouptype_priority"),
    ]

    operations = [
    ]
