# Generated by Django 4.2.20 on 2025-04-13 20:46

import apps.utils.fields.image_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0014_rename_admin_request_messsage_membership_admin_request_message_and_more_squashed_0016_grouptype_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='address',
            field=models.CharField(blank=True, max_length=250, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='group',
            name='latitude',
            field=models.CharField(blank=True, max_length=250, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='group',
            name='longitude',
            field=models.CharField(blank=True, max_length=250, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='grouptype',
            name='is_map',
            field=models.BooleanField(default=False, verbose_name='Is map'),
        ),
        migrations.AlterField(
            model_name='group',
            name='banner',
            field=apps.utils.fields.image_field.CustomImageField(blank=True, help_text='Image with 3:1 ratio (recommended minimum size: 1200x400)', null=True, verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='group',
            name='icon',
            field=apps.utils.fields.image_field.CustomImageField(blank=True, help_text='Image with a ratio of 1:1 (recommended minimum size: 500x500)', null=True, verbose_name='Profile picture'),
        ),
    ]
