# Generated by Django 4.1.5 on 2023-01-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0016_rename_group_by_label_grouptype_category_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptype',
            name='category_label_default',
            field=models.CharField(blank=True, max_length=30, verbose_name='Label de la catégorie par défaut'),
        ),
        migrations.AlterField(
            model_name='grouptype',
            name='is_year_group',
            field=models.BooleanField(default=False, help_text='Les groupes sont liés à une année scolaire. Aucunes dates ne sont demandées aux membres.', verbose_name='Groupes annuels'),
        ),
        migrations.AlterField(
            model_name='grouptype',
            name='slug',
            field=models.SlugField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
