# Generated by Django 4.1.5 on 2023-01-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_faculty'),
        ('sociallink', '0005_alter_sociallink_label_alter_sociallink_url'),
        ('group', '0017_grouptype_category_label_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscriptions', to='student.student', verbose_name='Abonnés'),
        ),
        migrations.AlterField(
            model_name='group',
            name='social_links',
            field=models.ManyToManyField(blank=True, related_name='+', to='sociallink.sociallink', verbose_name='Réseaux Sociaux'),
        ),
    ]
