# Generated by Django 4.2.20 on 2025-03-23 15:02

from django.db import migrations

import apps.utils.fields.image_field


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0017_merge_20250317_1623"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="banner",
            field=apps.utils.fields.image_field.CustomImageField(blank=True, help_text="Image with 3:1 ratio (recommended minimum size: 1200x400)", null=True, verbose_name="Banner"),
        ),
        migrations.AlterField(
            model_name="group",
            name="icon",
            field=apps.utils.fields.image_field.CustomImageField(blank=True, help_text="Image with a ratio of 1:1 (recommended minimum size: 500x500)", null=True, verbose_name="Profile picture"),
        ),
    ]
