# Generated by Django 4.2.23 on 2025-06-29 16:41
from django.db import migrations

from simple_history.utils import get_history_manager_for_model

from apps.group import models


def forwards(apps, schema_editor):
    Group = apps.get_model("group", "Group")

    history = get_history_manager_for_model(models.Group)

    for group in Group.objects.all():
        user = group.created_by.user if group.created_by else None
        group.versions.create(
            history_date=group.created_at,
            history_user=user,
            history_type="+",
            **{
                field.attname: getattr(group, field.attname)
                for field in history.model.tracked_fields
            },
        )

        if group.created_at != group.updated_at:
            user = group.updated_by.user if group.updated_by else None
            group.versions.create(
                history_date=group.updated_at,
                history_user=user,
                history_type="~",
                **{
                    field.attname: getattr(group, field.attname)
                    for field in history.model.tracked_fields
                },
            )


def reverse(apps, schema_editor):
    Group = apps.get_model("group", "Group")

    for group in Group.objects.all():
        version = group.versions.earliest()
        student = version.history_user.student if version.history_user else None
        group.created_at = version.history_date
        group.created_by = student

        version = group.versions.latest()
        student = version.history_user.student if version.history_user else None
        group.updated_at = version.history_date
        group.updated_by = student
        group.save()


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0018_add_historical_manager"),
    ]

    operations = [
        migrations.RunPython(forwards, reverse),
        migrations.RemoveField(
            model_name="group",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="group",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="group",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="group",
            name="updated_by",
        ),
    ]
