# Generated by Django 4.2.20 on 2025-04-15 20:26

from django.db import migrations
from django.utils import timezone


def transfert_roommates_to_group(apps, schema_editor):
    # Get the models
    GroupType = apps.get_model("group", "GroupType")
    Group = apps.get_model("group", "Group")
    Roommates = apps.get_model("roommates", "Roommates")
    Membership = apps.get_model("group", "Membership")

    # Create group type
    roommates_group_type = GroupType.objects.create(
        name="Colocations",
        slug="colocs",
        hide_no_active_members=True,
        can_create=True,
        can_have_parent=False,
    )

    # Transfer roommates to group
    for roommate in Roommates.objects.all():
        housing = roommate.housing
        group = Group.objects.create(
            name=roommate.name,
            short_name=roommate.alt_name,
            slug=roommate.slug,
            group_type=roommates_group_type,
            lock_memberships=True,
            creation_year=roommate.begin_date.year,
            archived=roommate.begin_date.year<timezone.now().year,
            summary=housing.details,
            description=roommate.summary + "\n" + roommate.description,
            icon=roommate.logo,
            banner=roommate.banniere,
            video1=roommate.video1,
            video2=roommate.video2,
            address=housing.address,
            latitude=str(housing.latitude),
            longitude=str(housing.longitude),
            created_at=roommate.begin_date,
            updated_at=roommate.modified_date,
        )

        # Transfer members
        for member in roommate.namedmembershiproommates_set.all():
            membership = Membership.objects.create(
                group=group,
                student=member.student,
                begin_date=roommate.begin_date,
                end_date=roommate.end_date,
                admin=member.admin,
                summary=member.nickname,
            )
            membership.save()


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0018_alter_group_address_alter_group_latitude_and_more"),
        ("roommates", "0017_alter_housing_details_and_more"),
    ]

    operations = [
        migrations.RunPython(transfert_roommates_to_group),
    ]
