# Generated by Django 4.1.5 on 2023-01-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0019_remove_group_anyone_can_join_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouptype',
            name='slug_is_name',
        ),
        migrations.AddField(
            model_name='grouptype',
            name='private_by_default',
            field=models.BooleanField(default=False, help_text='Les nouveaux groupes créés sont privés par défaut.', verbose_name='Privés par défaut'),
        ),
    ]
