# Generated by Django 4.2.23 on 2025-07-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0019_created_and_updated_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="address",
            field=models.CharField(
                blank=True, default="", max_length=250, verbose_name="Address"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="latitude",
            field=models.FloatField(
                blank=True,
                default=47.2186371,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="longitude",
            field=models.FloatField(
                blank=True,
                default=-1.5541362,
                null=True,
                verbose_name="Longitude",
            ),
        ),
        migrations.AddField(
            model_name="grouptype",
            name="is_map",
            field=models.BooleanField(default=False, verbose_name="Is map"),
        ),
    ]
