# Generated by Django 4.2.26 on 2026-01-07 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0020_group_address_group_latitude_group_longitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Thematic",
            fields=[
                (
                    "identifier",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "french_name",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="French Name"
                    ),
                ),
                (
                    "english_name",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="English Name"
                    ),
                ),
                ("priority", models.IntegerField(default=0, verbose_name="Priority")),
                ("visible", models.BooleanField(default=True)),
                ("public", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Thematic",
                "verbose_name_plural": "Thematics",
            },
        ),
        migrations.AddField(
            model_name="group",
            name="thematic",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="group.thematic",
            ),
        ),
    ]
