# Generated by Django 4.2.26 on 2026-02-25 12:48

import django.db.models.deletion
from django.db import migrations, models

import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0020_group_address_group_latitude_group_longitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Thematic",
            fields=[
                (
                    "identifier",
                    models.AutoField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Name"
                    ),
                ),
                (
                    "name_fr",
                    models.CharField(
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(default=0, verbose_name="Priority"),
                ),
                ("visible", models.BooleanField(default=True)),
                ("public", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Thematic",
                "verbose_name_plural": "Thematics",
            },
        ),
        migrations.AddField(
            model_name="group",
            name="description_en",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="description_fr",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="summary_en",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Summary"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="summary_fr",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Summary"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="thematic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="group.thematic",
            ),
        ),
        migrations.AddField(
            model_name="historicalgroup",
            name="thematic",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="group.thematic",
            ),
        ),
    ]
