# Generated by Django 4.2.26 on 2026-02-24 22:18

from django.db import migrations, models

import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0020_group_address_group_latitude_group_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="description_en",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="description_fr",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="summary_en",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Summary"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="summary_fr",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Summary"
            ),
        ),
    ]
