# Generated by Django 4.2.28 on 2026-02-07 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forward(apps, schema_editor):
    AdminRightsRequest = apps.get_model("group", "AdminRightsRequest")
    Group = apps.get_model("group", "Group")
    Membership = apps.get_model("group", "Membership")

    for admin_rights_request in AdminRightsRequest.objects.all():
        admin_rights_request.user = admin_rights_request.student.user
        admin_rights_request.save()

    for group in Group.objects.all():
        for subscriber in group.subscribers.all():
            group.subscribers_users.add(subscriber.user)
        group.save()

    for membership in Membership.objects.all():
        membership.user = membership.student.user
        membership.save()


def reverse(apps, schema_editor):
    AdminRightsRequest = apps.get_model("group", "AdminRightsRequest")
    Group = apps.get_model("group", "Group")
    Membership = apps.get_model("group", "Membership")

    for admin_rights_request in AdminRightsRequest.objects.all():
        admin_rights_request.student = admin_rights_request.user.student
        admin_rights_request.save()

    for group in Group.objects.all():
        for subscriber_user in group.subscribers_users.all():
            group.subscribers.add(subscriber_user.student)
        group.save()

    for membership in Membership.objects.all():
        membership.student = membership.user.student
        membership.save()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("group", "0020_group_address_group_latitude_group_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminrightsrequest",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="group",
            name="subscribers_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Subscribers",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membership_set",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(forward, reverse),
    ]
