# Generated by Django 4.1.5 on 2023-01-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0020_remove_grouptype_slug_is_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptype',
            name='extra_parents',
            field=models.ManyToManyField(blank=True, help_text='Les enfants de ces groupes seront affichés dans la liste des groupes.', related_name='+', to='group.group', verbose_name='Parents supplémentaires'),
        ),
    ]
