# Generated by Django 4.2.26 on 2026-01-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0021_thematic_group_thematic"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouptype",
            name="english_name",
            field=models.CharField(
                max_length=30, null=True, verbose_name="Type english name"
            ),
        ),
        migrations.AlterField(
            model_name="grouptype",
            name="name",
            field=models.CharField(
                max_length=30, unique=True, verbose_name="Type french name"
            ),
        ),
    ]
