# Generated by Django 4.2.26 on 2026-02-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0021_group_description_en_group_description_fr_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Thematic",
            fields=[
                (
                    "identifier",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="Name"),
                ),
                (
                    "name_fr",
                    models.CharField(
                        max_length=30, null=True, unique=True, verbose_name="Name"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=30, null=True, unique=True, verbose_name="Name"
                    ),
                ),
                ("priority", models.IntegerField(default=0, verbose_name="Priority")),
                ("visible", models.BooleanField(default=True)),
                ("public", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Thematic",
                "verbose_name_plural": "Thematics",
            },
        ),
    ]
