# Generated by Django 4.2.28 on 2026-02-07 17:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "group",
            "0021_adminrightsrequest_user_group_subscribers_users_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membership",
            options={
                "ordering": ["group", "-priority", "user"],
                "verbose_name": "membre",
            },
        ),
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together={("user", "group")},
        ),
        migrations.RemoveField(
            model_name="adminrightsrequest",
            name="student",
        ),
        migrations.RemoveField(
            model_name="group",
            name="subscribers",
        ),
        migrations.AlterField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="group_set",
                through="group.Membership",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Members",
            ),
        ),
        migrations.RemoveField(
            model_name="membership",
            name="student",
        ),
    ]
