# Generated by Django 4.2.26 on 2026-01-15 10:48

from django.db import migrations, models

import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0022_grouptype_english_name_alter_grouptype_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="english_description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="english_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="group",
            name="english_short_name",
            field=models.CharField(
                blank=True,
                help_text="This name will be used in the list of groups.",
                max_length=100,
                verbose_name="Short name",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="english_summary",
            field=models.CharField(blank=True, max_length=500, verbose_name="Summary"),
        ),
    ]
