# Generated by Django 4.2.28 on 2026-02-07 18:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0022_alter_membership_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="subscribers_users",
            new_name="subscribers",
        ),
    ]
