# Generated by Django 4.1.5 on 2023-01-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0022_alter_grouptype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptype',
            name='sort_fields',
            field=models.CharField(default='-order, short_name', help_text='Fields used to sort groups in the list. If categories are defined, you must reflect them here.', max_length=30, verbose_name='Sort Fields'),
        ),
    ]
