# Generated by Django 4.2.26 on 2026-01-15 11:07

from django.db import migrations, models

import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0023_group_english_description_group_english_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="French description"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="english_description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="English description"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="english_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="English name"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="english_short_name",
            field=models.CharField(
                blank=True,
                help_text="This name will be used in the list of groups.",
                max_length=100,
                verbose_name="English short name",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="english_summary",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="English summary"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="French name"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="short_name",
            field=models.CharField(
                blank=True,
                help_text="This name will be used in the list of groups.",
                max_length=100,
                verbose_name="French short name",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="summary",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="French summary"
            ),
        ),
        migrations.AlterField(
            model_name="historicalgroup",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="French description"
            ),
        ),
        migrations.AlterField(
            model_name="historicalgroup",
            name="name",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="French name"
            ),
        ),
        migrations.AlterField(
            model_name="historicalgroup",
            name="summary",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="French summary"
            ),
        ),
    ]
