# Generated by Django 4.2.26 on 2026-02-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0021_thematic_group_description_en_group_description_fr_and_more"),
        ("group", "0023_rename_subscribers_users_group_subscribers"),
    ]

    operations = []
