# Generated by Django 4.1.5 on 2023-01-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0023_alter_grouptype_sort_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptype',
            name='hide_no_active_members',
            field=models.BooleanField(default=False, help_text="Hide groups where all 'end_date' from members are past.", verbose_name='Hide groups without active members'),
        ),
    ]
