# Generated by Django 4.1.5 on 2023-01-23 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_faculty'),
        ('group', '0024_grouptype_hide_no_active_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='meeting_hour',
            field=models.CharField(blank=True, max_length=50, verbose_name='Meeting hours'),
        ),
        migrations.AddField(
            model_name='group',
            name='meeting_place',
            field=models.CharField(blank=True, max_length=50, verbose_name='Meeting place'),
        ),
        migrations.AlterField(
            model_name='grouptype',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Type name'),
        ),
        migrations.AlterField(
            model_name='grouptype',
            name='sort_fields',
            field=models.CharField(default='-order, short_name', help_text="Fields used to sort groups in the list, separated by ',' and without spaces. If categories are defined, you must also reflect them here.", max_length=100, verbose_name='Sort Fields'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_set', to='group.group'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_set', to='student.student'),
        ),
    ]
