# Generated by Django 4.2.26 on 2026-01-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0024_alter_group_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="description",
            new_name="french_description",
        ),
        migrations.RenameField(
            model_name="group",
            old_name="name",
            new_name="french_name",
        ),
        migrations.RenameField(
            model_name="group",
            old_name="short_name",
            new_name="french_short_name",
        ),
        migrations.RenameField(
            model_name="group",
            old_name="summary",
            new_name="french_summary",
        ),
        migrations.RenameField(
            model_name="historicalgroup",
            old_name="description",
            new_name="french_description",
        ),
        migrations.RenameField(
            model_name="historicalgroup",
            old_name="name",
            new_name="french_name",
        ),
        migrations.RenameField(
            model_name="historicalgroup",
            old_name="summary",
            new_name="french_summary",
        ),
    ]
