# Generated by Django 5.2.15 on 2026-08-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0024_alter_grouptype_is_map"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="can_create_sport_event",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Admin members of this group can create sport events",
                null=True,
                verbose_name="Can create sport events",
            ),
        ),
    ]
