# Generated by Django 4.2.26 on 2026-01-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0025_rename_description_group_french_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalgroup",
            name="french_description",
        ),
        migrations.RemoveField(
            model_name="historicalgroup",
            name="french_name",
        ),
        migrations.RemoveField(
            model_name="historicalgroup",
            name="french_summary",
        ),
        migrations.AlterField(
            model_name="group",
            name="french_summary",
            field=models.CharField(blank=True, default="", max_length=500, verbose_name="French summary"),
        ),
        migrations.AlterField(
            model_name="grouptype",
            name="english_name",
            field=models.CharField(blank=True, default="", max_length=30, verbose_name="Type english name"),
        ),
    ]
