# Generated by Django 4.1.5 on 2023-01-29 17:32

import apps.group.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0025_group_meeting_hour_group_meeting_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='begin_date',
            field=models.DateField(default=apps.group.models.today, verbose_name='Begin date'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateField(default=apps.group.models.one_year_later, verbose_name='End date'),
        ),
    ]
