# Generated by Django 4.1.6 on 2023-02-11 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0026_alter_membership_begin_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='restrict_membership',
        ),
    ]
