# Generated by Django 4.1.6 on 2023-02-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0027_remove_group_restrict_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='last_modified_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='last_modified_by',
            new_name='updated_by',
        ),
    ]
