# Generated by Django 4.1.3 on 2022-12-22 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0010_group_grouptype_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Nom de la carte')),
                ('slug', models.SlugField(max_length=10, primary_key=True, serialize=False, verbose_name='Abréviation du type')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250, verbose_name='Adresse')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('_name', models.CharField(blank=True, max_length=50, verbose_name='Nom du lieu')),
                ('_summary', models.CharField(blank=True, max_length=200, null=True, verbose_name='Résumé')),
                ('most_recent_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='group.group')),
                ('place_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.map')),
            ],
        ),
    ]
