# Generated by Django 4.2.28 on 2026-03-03 15:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FormSchema",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("schema", models.JSONField()),
                ("ui_schema", models.JSONField(blank=True, null=True)),
                ("i18n_en_keys", models.JSONField(blank=True, null=True)),
                ("i18n_fr_keys", models.JSONField(blank=True, null=True)),
                ("editable", models.BooleanField(default=True)),
                ("public", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("editor", "Editor"),
                            ("answer_viewer", "Answer Viewer"),
                            ("form_viewer", "Form Viewer"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "form_schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="form.formschema",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "form_schema")},
            },
        ),
        migrations.AddField(
            model_name="formschema",
            name="users",
            field=models.ManyToManyField(
                related_name="form_schemas",
                through="form.UserRole",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="FormAnswer",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data", models.JSONField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "form_schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="form.formschema",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
