# Generated by Django 4.2.28 on 2026-03-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formschema',
            old_name='i18n_en_keys',
            new_name='i18n_keys_en',
        ),
        migrations.RenameField(
            model_name='formschema',
            old_name='i18n_fr_keys',
            new_name='i18n_keys_fr',
        ),
    ]
