# Generated by Django 5.2.17 on 2026-09-10 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0002_rename_i18n_en_keys_formschema_i18n_keys_en_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="formschema",
            name="active",
            field=models.BooleanField(
                default=False,
                verbose_name="Are people allowed to answer the form",
            ),
        ),
        migrations.AlterField(
            model_name="formschema",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="formschema",
            name="editable",
            field=models.BooleanField(
                default=True, verbose_name="Can editors edit the form"
            ),
        ),
        migrations.AlterField(
            model_name="formschema",
            name="public",
            field=models.BooleanField(
                default=False,
                verbose_name="Are people able to get the form with only the URL",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="formanswer",
            unique_together={("form_schema", "user")},
        ),
    ]
