# Generated by Django 3.2.3 on 2021-06-12 21:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("roommates", "0002_auto_modified_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roommates",
            name="parent",
        ),
    ]
