# Generated by Django 4.2.13 on 2024-05-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roommates", "0016_alter_roommates_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="housing",
            name="details",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Complément d'adresse",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="namedmembershiproommates",
            name="nickname",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Surnom"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="roommates",
            name="alt_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Nom alternatif",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="roommates",
            name="colocathlon_activities",
            field=models.CharField(
                blank=True,
                default="",
                max_length=250,
                verbose_name="Activités proposées",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="roommates",
            name="colocathlon_hours",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Horaires d'ouvertures",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="roommates",
            name="summary",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="Résumé"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="roommates",
            name="video1",
            field=models.URLField(
                blank=True, default="", verbose_name="Lien vidéo 1"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="roommates",
            name="video2",
            field=models.URLField(
                blank=True, default="", verbose_name="Lien vidéo 2"
            ),
            preserve_default=False,
        ),
    ]
