# Generated by Django 3.2.3 on 2021-06-05 21:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0002_rename_dd_cursus_add_alternant"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["first_name", "last_name"]},
        ),
    ]
