# Generated by Django 3.2.4 on 2021-07-14 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0003_alter_student_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["last_name", "first_name"]},
        ),
    ]
