# Generated by Django 3.2.4 on 2021-08-01 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0004_alter_student_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["user__last_name", "user__first_name"]},
        ),
        migrations.RemoveField(
            model_name="student",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="last_name",
        ),
    ]
