# Generated by Django 4.1.2 on 2022-11-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0005_auto_20210801_1726"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="faculty",
            field=models.CharField(
                choices=[
                    ("Gen", "Élève Ingénieur Généraliste"),
                    ("Iti", "Élève Ingénieur de Spécialité (ITII)"),
                    ("Mas", "Élève en Master"),
                    ("Doc", "Doctorant"),
                ],
                max_length=200,
                verbose_name="Filière",
            ),
        ),
    ]
