# Generated by Django 4.2.4 on 2023-09-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0006_alter_student_faculty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="faculty",
            field=models.CharField(
                choices=[
                    ("Gen", "Ingénieur Généraliste"),
                    ("Iti", "Ingénieur de Spécialité (ITII)"),
                    ("Mas", "Master"),
                    ("Doc", "Doctorat"),
                    ("Bac", "Bachelor"),
                    ("MSp", "Mastère Spécialisé"),
                ],
                max_length=200,
                verbose_name="Filière",
            ),
        ),
    ]
