# Generated by Django 4.2.13 on 2024-08-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sociallink", "0005_alter_sociallink_label_alter_sociallink_url"),
        ("student", "0008_alter_student_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="description",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="student",
            name="social_links",
            field=models.ManyToManyField(
                blank=True,
                related_name="student_set",
                to="sociallink.sociallink",
                verbose_name="Réseaux Sociaux",
            ),
        ),
    ]
