# Generated by Django 3.2.11 on 2022-01-29 17:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0005_auto_20210801_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=255, verbose_name='Corps')),
                ('url', models.CharField(max_length=255, verbose_name='Cible')),
                ('owner', models.SlugField(verbose_name='Page parente')),
                ('publicity', models.CharField(choices=[('Pub', 'Public - Visible par tous'), ('Mem', 'Membres uniquement - Visible uniquement par les membres du groupe'), ('Adm', 'Administeurs de la page')], default='Pub', max_length=3, verbose_name='Visibilité de la notification')),
                ('action1_label', models.CharField(blank=True, max_length=20, null=True, verbose_name='Action 1 - Label')),
                ('action1_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Action 1 - Cible')),
                ('action2_label', models.CharField(blank=True, max_length=20, null=True, verbose_name='Action 1 - Label')),
                ('action2_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Action 1 - Cible')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('high_priority', models.BooleanField(default=False, verbose_name='Prioritaire')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.SlugField(verbose_name='Page')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'unique_together': {('student', 'page')},
            },
        ),
        migrations.CreateModel(
            name='SentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False, verbose_name='Vu')),
                ('subscribed', models.BooleanField(default=False, help_text='Vrai si on la montre dans les abonnements', verbose_name='Abonné')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.notification')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'verbose_name': 'Notification envoyée',
                'verbose_name_plural': 'Notifications envoyées',
                'unique_together': {('student', 'notification')},
            },
        ),
    ]
