# Generated by Django 3.2.12 on 2022-04-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='publicity',
            field=models.CharField(choices=[('Pub', 'Public - Visible par tous'), ('Mem', 'Membres uniquement - Visible uniquement par les membres du groupe'), ('Adm', 'Administeurs de la page')], default='Pub', max_length=3, verbose_name='Visibilité de la notification'),
        ),
    ]
