# Generated by Django 3.2.5 on 2021-11-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.SlugField(max_length=255, verbose_name='Cible'),
        ),
    ]
