# Generated by Django 3.2.5 on 2021-11-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20211117_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.CharField(max_length=255, verbose_name='Cible'),
        ),
    ]
