# Generated by Django 3.2.5 on 2021-12-04 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_receiveallnotifications'),
        ('notification', '0003_alter_notification_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False, verbose_name='Vu')),
                ('subscribed', models.BooleanField(default=False, help_text='Vrai si on la montre dans les abonnements', verbose_name='Abonné')),
            ],
            options={
                'verbose_name': 'Notification envoyée',
                'verbose_name_plural': 'Notifications envoyées',
            },
        ),
        migrations.RemoveField(
            model_name='notification',
            name='group',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='receivers',
        ),
        migrations.AddField(
            model_name='notification',
            name='owner',
            field=models.SlugField(default='club--bde', verbose_name='Page parente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='publicity',
            field=models.CharField(choices=[('Pub', 'Public - Visible par tous'), ('Mem', 'Membres uniquement - Visible uniquement par les membres du groupe'), ('Adm', 'Administeurs de la page')], default='Pub', max_length=3, verbose_name='Visibilité de la notification'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='page',
            field=models.SlugField(default='club--bde', verbose_name='Page'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('student', 'page')},
        ),
        migrations.DeleteModel(
            name='ReceivedNotification',
        ),
        migrations.AddField(
            model_name='sentnotification',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivers', to='notification.notification'),
        ),
        migrations.AddField(
            model_name='sentnotification',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='group',
        ),
        migrations.AlterUniqueTogether(
            name='sentnotification',
            unique_together={('student', 'notification')},
        ),
    ]
