# Generated by Django 3.2.5 on 2021-12-05 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210801_1726'),
        ('notification', '0004_auto_20211204_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='receivers',
            field=models.ManyToManyField(related_name='notification_set', through='notification.SentNotification', to='student.Student'),
        ),
        migrations.AlterField(
            model_name='sentnotification',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.notification'),
        ),
    ]
