# Generated by Django 4.1.7 on 2023-02-22 11:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("liste", "0016_alter_namedmembershiplist_unique_together_and_more"),
        ("club", "0002_migrate_to_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="club",
            name="bdx_type",
        ),
        migrations.RemoveField(
            model_name="club",
            name="members",
        ),
        migrations.RemoveField(
            model_name="namedmembershipclub",
            name="group",
        ),
        migrations.RemoveField(
            model_name="namedmembershipclub",
            name="student",
        ),
        migrations.DeleteModel(
            name="BDX",
        ),
        migrations.DeleteModel(
            name="Club",
        ),
        migrations.DeleteModel(
            name="NamedMembershipClub",
        ),
    ]
