# Generated by Django 3.2.4 on 2021-08-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0012_alter_club_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="namedmembershipclub",
            name="date_end",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de fin (facultatif)"
            ),
        ),
        migrations.AlterField(
            model_name="namedmembershipclub",
            name="function",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Rôle (facultatif)"
            ),
        ),
    ]
