# Generated by Django 3.2.4 on 2021-08-06 09:38

from django.db import migrations, models

import apps.utils.upload


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0013_auto_20210805_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='banniere',
            field=models.ImageField(blank=True, help_text='Votre bannière sera affichée au format 1320x492 pixels.', null=True, upload_to=apps.utils.upload.PathAndRename('groups/banniere'), verbose_name='Bannière'),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, help_text='Votre logo sera affiché au format 306x306 pixels.', null=True, upload_to=apps.utils.upload.PathAndRename('groups/logo'), verbose_name='Logo du groupe'),
        ),
    ]
