name: Build Email Templates

on:
  workflow_call:
    inputs:
      target-directory:
        required: true
        type: string

jobs:
  email-templates-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: email-templates-generator

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: email-templates-generator/.nvmrc
          cache: npm
          cache-dependency-path: email-templates-generator/package-lock.json

      - name: Install dependencies
        run: npm ci --omit=dev

      - name: Build email templates
        run: npm run build

      - name: Upload files to the VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.INSTANCE_ADDRESS }}
          username: "ubuntu"
          key: ${{ secrets.SSH_KEY_DEPLOY }}
          source: "backend/templates/emails/*"
          target: ${{ inputs.target-directory }}
