name: Deploy Docs

on:
  push:
    branches:
      - master
    paths:
      - docs/**
      - .github/workflows/deploy-docs.yml

jobs:
  deploy:
    name: Deploy docs to GitHub Pages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: docs/.nvmrc

      - name: Install dependencies
        run: npm ci
      - name: Update dates and authors
        run: ./update_headers.sh
      - name: Build website
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          user_name: nantralplatform-bot
          user_email: nantralplatform@gmail.com
