name: Deploy Staging

on:
  workflow_dispatch:

jobs:
  frontend-quality:
    name: Test front end quality
    uses: ./.github/workflows/quality-frontend.yml
    secrets: inherit

  backend-quality:
    name: Test Back End Quality
    uses: ./.github/workflows/quality-backend.yml
    secrets: inherit

  email-templates-quality:
    name: Test Email Templates Quality
    uses: ./.github/workflows/quality-email-templates.yml
    secrets: inherit

  frontend-build:
    name: Build front end
    needs: frontend-quality
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: frontend/.nvmrc
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci --omit=dev

      - name: Build React
        run: npm run build

      - name: Upload files to the VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.INSTANCE_ADDRESS }}
          username: "ubuntu"
          key: ${{ secrets.SSH_KEY_DEPLOY }}
          source: "backend/static/front/*"
          target: "nantralPlatform-staging"

  email-templates-build:
    name: Build email templates
    needs: email-templates-quality
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: email-templates-generator

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: email-templates-generator/.nvmrc
          cache: npm
          cache-dependency-path: email-templates-generator/package-lock.json

      - name: Install dependencies
        run: npm ci --omit=dev

      - name: Build email templates
        run: npm run build

      - name: Upload files to the VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.INSTANCE_ADDRESS }}
          username: "ubuntu"
          key: ${{ secrets.SSH_KEY_DEPLOY }}
          source: "backend/templates/emails/*"
          target: "nantralPlatform-staging"

  clone-database:
    name: Make a copy of the database
    runs-on: ubuntu-latest
    steps:
      - name: Clone the prod database to staging database
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.INSTANCE_ADDRESS }}
          username: "ubuntu"
          key: ${{ secrets.SSH_KEY_DEPLOY }}
          script: |
            cd nantralPlatform/deployment/scripts
            sudo apt-get install python3-psycopg2 -y
            python3 -m venv env
            source env/bin/activate
            pip install -r requirements.txt
            python3 db_staging.py
            deactivate
            rm -r env

  deploy:
    name: Deploy to staging
    needs:
      [frontend-build, email-templates-build, backend-quality, clone-database]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to the VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.INSTANCE_ADDRESS }}
          username: "ubuntu"
          key: ${{ secrets.SSH_KEY_DEPLOY }}
          script: |
            cd nantralPlatform-staging/deployement
            git fetch origin ${{ github.ref_name }}:${{ github.ref_name }}
            git switch ${{ github.ref_name }}
            git reset --hard origin/${{ github.ref_name }}
            sudo docker-compose -f docker-compose.yml -f docker-compose.prod.yml build backend-staging
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
