name: Deploy Docs

on:
  push:
    branches:
      - master
    paths:
      - docs/**
      - .github/workflows/deploy-docs.yml

defaults:
  run:
    working-directory: docs

jobs:
  deploy:
    name: Deploy docs to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: latest
          cache: npm
          cache-dependency-path: docs/

      - name: Install dependencies
        run: npm ci --omit=dev

      - name: Build website
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          user_name: nantralplatform-bot
          user_email: nantralplatform@gmail.com
