name: Deploy Staging

on:
  push:
    branches:
      - staging
    paths:
      - backend/**
      - deployment/**
      - frontend/**
      - .github/workflows/deploy-staging.yml

jobs:
  frontend-build:
    name: Build React bundles
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest commit
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: frontend/.nvmrc
      - name: Build React
        run: |
          cd frontend
          npm install --omit=dev
          npm run build
      - name: Upload files to the VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.INSTANCE_ADDRESS }}
          username: "ubuntu"
          key: ${{ secrets.SSH_KEY_DEPLOY }}
          source: "backend/static/js/*/**.js"
          target: "nantralPlatform-staging"

  clone-database:
    runs-on: ubuntu-latest
    steps:
      - name: Clone before staging
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.INSTANCE_ADDRESS }}
          username: "ubuntu"
          key: ${{ secrets.SSH_KEY_DEPLOY }}
          script: |
            cd nantralPlatform/deployment/scripts
            sudo apt-get install python3-psycopg2 -y
            python3 -m venv env
            source env/bin/activate
            pip install -r requirements.txt
            python3 db_staging.py
            deactivate
            rm -r env

  deploy:
    needs: [frontend-build, clone-database]
    runs-on: ubuntu-latest

    steps:
      - name: Pull latest commit
        uses: actions/checkout@v3
      - name: Deploy to the VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.INSTANCE_ADDRESS }}
          username: "ubuntu"
          key: ${{ secrets.SSH_KEY_DEPLOY }}
          script: |
            cd nantralPlatform-staging/deployment
            git checkout staging && git pull origin staging
            cd ~/nantralPlatform/deployment
            sudo docker-compose -f docker-compose.yml -f docker-compose.prod.yml build backend-staging
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
