# This is a basic workflow to help you get started with Actions

name: EC2 Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: 'test'
      run: echo ${{ secrets.SSH_KEY_DEPLOY }}

    # Runs a set of commands using the runners shell
    - name: Deploy to a foreign instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.INSTANCE_ADDRESS }}
        username: "ec2-user"
        key: ${{ secrets.SSH_KEY_DEPLOY }}
        script: |
          cd nantralPlatform
          cd deployment
          docker-compose down
          git pull master
          docker-compose up -d
