name: Test Back End Quality

on: workflow_call

jobs:
  backend-quality:
    name: Back End Quality
    runs-on: ubuntu-latest

    defaults:
      run:
        # default directory for 'run' actions only in steps
        working-directory: backend

    steps:
      - name: Pull latest commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # History of commits needed for SonarCloud

      - name: Setup Node for email templates
        uses: actions/setup-node@v3
        with:
          node-version-file: email-templates-generator/.nvmrc
          cache: npm
          cache-dependency-path: email-templates-generator/package-lock.json

      - name: Build email templates
        run: |
          cd ../email-templates-generator
          npm ci
          npm run build

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: backend/.python-version
          cache: pipenv
          cache-dependency-path: backend/Pipfile.lock

      - name: Install dependencies
        run: |
          curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
          pipenv verify
          pipenv sync --dev

      - name: Linter
        run: |
          pipenv run lint

      - name: Run tests and collect coverage
        run: |
          pipenv run test:coverage
          pipenv run coverage xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: backend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACKEND }}
