name: Quality Tests

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: Check changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
      docs: ${{ steps.filter.outputs.docs }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'
            docs:
              - 'docs/**'

  backend:
    name: Back End Quality
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    uses: ./.github/workflows/quality-backend.yml
    secrets: inherit

  frontend:
    name: Front End Quality
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    uses: ./.github/workflows/quality-frontend.yml
    secrets: inherit

  docs:
    name: Docs Quality
    needs: changes
    if: ${{ needs.changes.outputs.docs == 'true' }}
    uses: ./.github/workflows/quality-docs.yml
    secrets: inherit

  final-check:
    name: Final Check
    needs: [backend, frontend, docs]
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Check final status
        id: check-final-status
        run: exit 0
