name: Test Front End Quality

on: workflow_call

jobs:
  frontend-quality:
    name: Front End Quality
    runs-on: ubuntu-latest

    defaults:
      run:
        # default directory for 'run' actions only in steps
        working-directory: frontend

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
        with:
          # Shallow clones should be disabled for a better relevancy of analysis
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: frontend/.nvmrc
          cache: npm
          cache-dependency-path: frontend/

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test -- --coverage

      - name: Run SonarCloud scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: frontend/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONTEND }}
