name: Testing Docs

on:
  pull_request:
    branches:
      - master
    paths:
      - docs/**
      - .github/workflows/test-docs.yml

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci
      - name: Test build website
        run: npm run build
