name: Test Docs

on:
  pull_request:
    paths:
      - docs/**
      - .github/workflows/test-docs.yml

defaults:
  run:
    working-directory: docs

jobs:
  test-docs:
    name: Test docs
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm
          cache-dependency-path: docs/

      - name: Install dependencies
        run: npm ci --omit=dev

      - name: Build website
        run: npm run build
