name: Test Backend

on:
  push:
    paths: [backend/**]
    branches:
      - master
      - react-app
  pull_request:
    types: [opened, synchronize, reopened]
    paths: [backend/**]

defaults:
  run:
    working-directory: backend

jobs:
  test-backend:
    name: Tests on back end
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
        with:
          # Shallow clones should be disabled for a better relevancy of analysis
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pipenv

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python

      - name: Install dependencies
        run: |
          pipenv verify && pipenv sync
          pipenv run pip install coverage

      - name: Run tests
        run: |
          pipenv run coverage-test
          pipenv run coverage xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: backend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACKEND }}
