# Generated by Django 3.2.13 on 2022-05-19 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0004_auto_20211003_1523'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Affichage',
        ),
    ]
