# Generated by Django 4.1.2 on 2022-11-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0006_auto_20220822_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupquestion',
            name='coeff',
            field=models.IntegerField(verbose_name='Coefficient'),
        ),
        migrations.AlterField(
            model_name='questionmember',
            name='coeff',
            field=models.IntegerField(verbose_name='Coefficient'),
        ),
    ]
