# Generated by Django 4.2.13 on 2024-05-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0008_alter_family_banniere_alter_family_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basequestion",
            name="details",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Informations supplémentaires",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="basequestion",
            name="details_en",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Informations supplémentaires (en)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="family",
            name="alt_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Nom alternatif"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="family",
            name="non_subscribed_members",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Si certains des membres de la famille ne sont pas inscrits             sur Nantral Platform, vous pouvez les ajouter ici. Séparez les             noms par des VIRGULES !!!",
                max_length=300,
                verbose_name="Autres parrains",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="family",
            name="summary",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="Résumé"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="family",
            name="video1",
            field=models.URLField(blank=True, default="", verbose_name="Lien vidéo 1"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="family",
            name="video2",
            field=models.URLField(blank=True, default="", verbose_name="Lien vidéo 2"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="questionpage",
            name="details1A",
            field=models.TextField(blank=True, default="", verbose_name="Infos 1A"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="questionpage",
            name="details1A_en",
            field=models.TextField(
                blank=True, default="", verbose_name="Infos 1A (en)"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="questionpage",
            name="details2A",
            field=models.TextField(blank=True, default="", verbose_name="Infos 2A+"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="questionpage",
            name="details2A_en",
            field=models.TextField(
                blank=True, default="", verbose_name="Infos 2A+ (en)"
            ),
            preserve_default=False,
        ),
    ]
