# Generated by Django 4.2.13 on 2024-08-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0009_alter_basequestion_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answerfamily",
            name="custom_coeff",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="answermember",
            name="custom_coeff",
            field=models.FloatField(default=1.0),
        ),
    ]
