# Generated by Django 4.2.13 on 2024-08-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("family", "0009_alter_basequestion_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answerfamily",
            name="custom_coeff",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="answermember",
            name="custom_coeff",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="basequestion",
            name="allow_custom_coef",
            field=models.BooleanField(
                default=False,
                verbose_name="Coefficient personnalisable par la personne répondant",
            ),
        ),
    ]
