# Generated by Django 4.2.13 on 2024-08-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0011_alter_answerfamily_custom_coeff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="allow_custom_coeff",
            field=models.BooleanField(default=True),
        ),
    ]
