# Generated by Django 4.2.28 on 2026-02-07 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forward(apps, schema_editor):
    MembershipFamily = apps.get_model("family", "MembershipFamily")

    for membership in MembershipFamily.objects.all():
        membership.user = membership.student.user
        membership.save()


def reverse(apps, schema_editor):
    MembershipFamily = apps.get_model("family", "MembershipFamily")

    for membership in MembershipFamily.objects.all():
        membership.student = membership.user.student
        membership.save()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("family", "0011_remove_basequestion_allow_custom_coef_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipfamily",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membershipfamily",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Parrain/Marraine",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(forward, reverse),
    ]
