# Generated by Django 4.2.13 on 2024-08-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0012_option_allow_custom_coeff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="option",
            name="allow_custom_coeff",
        ),
        migrations.AddField(
            model_name="basequestion",
            name="allow_custom_coef",
            field=models.BooleanField(
                default=True, verbose_name="Coefficient personnalisable"
            ),
        ),
    ]
