# Generated by Django 4.2.13 on 2024-08-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0013_remove_option_allow_custom_coeff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basequestion",
            name="allow_custom_coef",
            field=models.BooleanField(
                default=False,
                verbose_name="Coefficient personnalisable par la personne répondant",
            ),
        ),
    ]
