# Generated by Django 4.2.13 on 2024-08-02 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0014_alter_basequestion_allow_custom_coef"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basequestion",
            name="allow_custom_coef",
        ),
    ]
