# Generated by Django 4.2.13 on 2024-08-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0015_remove_basequestion_allow_custom_coef"),
    ]

    operations = [
        migrations.AddField(
            model_name="basequestion",
            name="allow_custom_coef",
            field=models.BooleanField(
                default=False,
                verbose_name="Coefficient personnalisable par la personne répondant",
            ),
        ),
    ]
