# Generated by Django 4.2.13 on 2024-08-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0016_basequestion_allow_custom_coef"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answerfamily",
            name="custom_coeff",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="answermember",
            name="custom_coeff",
            field=models.IntegerField(default=1),
        ),
    ]
