# Generated by Django 3.0.5 on 2020-05-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name="Date de l'evenement")),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'evenemet")),
                ('description', models.TextField(verbose_name="Description de l'evenement")),
                ('location', models.CharField(max_length=200, verbose_name='Lieu')),
                ('publicity', models.CharField(choices=[('Pub', 'Public -- Visible par tous'), ('Mem', 'Membres -- Visibles uniquement par les membres du groupe')], max_length=200, verbose_name="Visibilité de l'evenement")),
                ('group', models.SlugField(verbose_name='Groupe organisateur')),
            ],
        ),
    ]
