# Generated by Django 3.0.8 on 2020-10-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_baseevent_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseevent',
            name='color',
            field=models.CharField(choices=[('primary', 'Bleu'), ('success', 'Vert'), ('danger', 'Rouge'), ('warning', 'Jaune'), ('secondary', 'Gris'), ('dark', 'Noir')], default='primary', max_length=200, null=True, verbose_name='Couleur de fond'),
        ),
    ]
