# Generated by Django 3.0.8 on 2021-03-12 21:21

import apps.utils.upload
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20201107_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseevent',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 21, 21, 3, 136306), verbose_name='Date de publication'),
        ),
        migrations.AlterField(
            model_name='baseevent',
            name='description',
            field=models.TextField(verbose_name="Texte de l'annonce"),
        ),
        migrations.AlterField(
            model_name='baseevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.utils.upload.PathAndRename('posts/pictures'), verbose_name="Une image, une affiche en lien avec l'evenement ?"),
        ),
        migrations.AlterField(
            model_name='baseevent',
            name='publicity',
            field=models.CharField(choices=[('Pub', 'Public - Visible par tous'), ('Mem', 'Membres uniquement - Visible uniquement par les membres du groupe')], max_length=200, verbose_name="Visibilité de l'annonce"),
        ),
        migrations.AlterField(
            model_name='baseevent',
            name='title',
            field=models.CharField(max_length=200, verbose_name="Titre de l'annonce"),
        ),
    ]
