# Generated by Django 3.0.14 on 2021-04-20 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20210405_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseevent',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 19, 27, 42, 393234), verbose_name='Date de publication'),
        ),
    ]
