# Generated by Django 3.0.8 on 2021-04-05 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20210312_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseevent',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 5, 15, 3, 41, 729677), verbose_name='Date de publication'),
        ),
    ]
