# Generated by Django 3.2.12 on 2022-04-15 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
        ('event', '0008_alter_baseevent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseevent',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification.notification'),
        ),
    ]
