# Generated by Django 3.0.5 on 2020-05-07 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo', models.IntegerField(blank=True, null=True, verbose_name='Année de promotion')),
                ('first_name', models.CharField(max_length=200, null=True, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=200, null=True, verbose_name='Nom de famille')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
