# Generated by Django 3.0.5 on 2020-04-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='promo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Année de promotion'),
        ),
    ]
