# Generated by Django 3.0.14 on 2021-05-24 21:44

import apps.utils.upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_dd_cursus_add_alternant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=apps.utils.upload.PathAndRename('./static/upload/students/profile_pictures'), verbose_name='Photo de profil'),
        ),
    ]
