# Generated by Django 3.0.5 on 2020-04-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200421_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Prénom'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Nom de famille'),
        ),
    ]
