# Generated by Django 3.0.5 on 2020-05-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200508_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='double_degree',
            field=models.CharField(blank=True, choices=[('Cla', ''), ('I-A', 'Ingénieur-Architect'), ('A-I', 'Architect-Ingenieur'), ('I-M', 'Ingenieur-Manager'), ('M-I', 'Manager-Ingénieur'), ('I-O', 'Ingénieur-Officier'), ('O-I', 'Officier-Ingénieur')], max_length=200, null=True, verbose_name='Double-cursus'),
        ),
    ]
