# Generated by Django 3.0.5 on 2020-05-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200514_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='students/profile_pictures', verbose_name='Photo de profil'),
        ),
    ]
