# Generated by Django 3.2.5 on 2021-11-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210801_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='receiveAllNotifications',
            field=models.BooleanField(default=True, help_text="Recevoir aussi les notifications des groupes auxquels vous n'êtes pas abonnés.", verbose_name='Recevoir toutes les notifications'),
        ),
    ]
