# Generated by Django 3.0.5 on 2020-06-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20200520_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='double_degree',
            field=models.CharField(blank=True, choices=[('', 'Cla'), ('Ingénieur-Architecte', 'I-A'), ('Architecte-Ingénieur', 'A-I'), ('Ingénieur-Manager', 'I-M'), ('Manager-Ingénieur', 'M-I'), ('Ingénieur-Officier', 'I-O'), ('Officier-Ingénieur', 'O-I')], max_length=200, null=True, verbose_name='Double cursus'),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(choices=[('Élève Ingénieur Généraliste', 'Gen'), ('Élève Ingénieur de Specialité (ITII)', 'Iti'), ('Élève en Master', 'Mas'), ('Doctorant', 'Doc')], max_length=200, verbose_name='Filière'),
        ),
        migrations.AlterField(
            model_name='student',
            name='promo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Année de promotion entrante'),
        ),
    ]
