# Generated by Django 3.0.5 on 2020-06-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20200601_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='double_degree',
            field=models.CharField(blank=True, choices=[('Cla', ''), ('I-A', 'Ingénieur-Architecte'), ('A-I', 'Architecte-Ingénieur'), ('I-M', 'Ingénieur-Manager'), ('M-I', 'Manager-Ingénieur'), ('I-O', 'Ingénieur-Officier'), ('O-I', 'Officier-Ingénieur')], max_length=200, null=True, verbose_name='Double cursus'),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(choices=[('Gen', 'Élève Ingénieur Généraliste'), ('Iti', 'Élève Ingénieur de Specialité (ITII)'), ('Mas', 'Élève en Master'), ('Doc', 'Doctorant')], max_length=200, verbose_name='Filière'),
        ),
    ]
